- rules-reviewed/eap7/eap6/tests/data/data2/ejb-jar.xml
- rules-reviewed/eap7/eap6/tests/eap6-xml.windup.test.xml
> WINDUPRULE-109: The rule for CMP entity EJBs doesn't catch ejb-jar.xml

- rules-reviewed/eap6/weblogic/weblogic-xml-descriptors.windup.xml
…the following:
https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.4/html-single/Administration_and_Configuration_Guide/index.html#sect-Configuration
This URL leads to configuration information for Hibernate. i.e. it is the wrong URL. The correct URL is the following:
https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.4/html-single/Administration_and_Configuration_Guide/index.html#sect-Configuration1
This URL goes to the JMS Configuration information section of the document, which is what is required. The "1" at the end of the URL is the only difference the two URLs
> URL Correction for JMS Configuration documentation

- .gitignore
- rules-reviewed/eap6/jrun/jrun-catchall.windup.xml
- rules-reviewed/eap6/uncategorized/generic-catchall.windup.xml
- rules-reviewed/eap6/weblogic/weblogic-catchall.windup.xml
- rules-reviewed/eap6/websphere/websphere-catchall.windup.xml
- rules-reviewed/fuse/sonic-catchall.windup.xml
I'm giving them "Potential" severity, as it seems that's what the user really wants. Correct me if I am wrong.
> WINDUPRULE-137  Catchall rules should have Optional severity

- pom.xml
@Ladicek found that the Enum constant discovery fails so I realized that the api-jars for EAP7 are not there.
> WINDUPRULE-169 - EAP 7 api jars inclusion into package jar

- rules-reviewed/os/windows/os-specific.windup.xml
Also rewording help text, if new wording looks OK
> fix jspf->jpsf typo in windows path rule

- rules-reviewed/eap6/uncategorized/environment-dependent.windup.xml
Per discussion with Jess, Robb, Marc Z; no objections. Won't fix the entire issue with this rule, but will at least stop it from dominating the story points wherever it shows up and making the overall estimates useless.
> revert dynamic instantiation rule to optional with 0 effort

- rules-reviewed/eap6/weblogic/weblogic-catchall.windup.xml
- rules-reviewed/eap6/websphere/websphere-catchall.windup.xml
When a catchall rule triggers in an application, it tends to trigger many times. This makes catchall rules with effort tend to dominate story point counts in a way that makes them less useful. It also causes performance problems on large applications by attaching effort to many thousands of issues.
Command used to check for instances of catchalls with effort:
d^@^:windup-rulesets$ find rules-reviewed -name "*.windup.xml" | grep catchall | xargs grep effort | grep -v "effort=\"0\""
rules-reviewed/eap6/websphere/websphere-catchall.windup.xml:                        <hint title="IBM proprietary type reference" effort="1" severity="potential">
rules-reviewed/eap6/websphere/websphere-catchall.windup.xml:                        <hint title="IBM ILog proprietary type reference" effort="1" …
> Remove effort from catchall rules.

- rules-reviewed/eap6/websphere/websphere-xml.windup.xml
There's a separate eap7-websphere-xml for EAP 7. Noticed this ruleset caused duplicate hits in a test app.
> Don't trigger eap6's websphere-xml ruleset for EAP 7.

- rules-reviewed/openshift/java-rmi.windup.xml
- rules-reviewed/openshift/local-storage.windup.xml
- rules-reviewed/openshift/logging.windup.xml
- rules-reviewed/openshift/mail.windup.xml
- rules-reviewed/openshift/session.windup.xml
`cloud-readiness` it the target id used for cloud-related rules instead of `openshift` ([see release notes](https://access.redhat.com/articles/2991361))
> T978 Remove the tag targetTechnology "openshift" from the rules that have it

- rules-reviewed/eap6/weblogic/tests/weblogic-catchall.windup.test.xml
- rules-reviewed/eap6/weblogic/weblogic-catchall.windup.xml
- fixed `weblogic-catchall-06000-test` test to cover `weblogic-catchall-07000` rule's case
- merged `weblogic-catchall-07000` rule in `weblogic-catchall-02000` rule making `com` prefix optional
- changed `weblogic-catchall-02000` rule's title to “Oracle proprietary type reference”
- switched position of rules `weblogic-catchall-02000` and `weblogic-catchall-06000` otherwise merged rule `weblogic-catchall-02000` would have fired also for `oracle.sql` classes
> T1012 Rule 'weblogic-catchall-02000' wording and merging

- rules-reviewed/openshift/local-storage.windup.xml
To avoid further false negatives, rule `local-storage-00003` does not search for path in `js` files anymore.
> WINDUPRULE-224 Removing 'js' extension from local storage rule

- rules-reviewed/eap7/eap6/hsearch.windup.xml
Added the name of the package to migrate to in hint's title to avoid giving the perception of duplicates rules and help the user to better address and understand the needed changes.
> WINDUPRULE-233 Lucene rules: improving hint's titles

- rules-reviewed/eap6/java-ee/seam/seam-java.windup.xml
- rules-reviewed/eap6/java-ee/seam/tests/data/src/ConversationTest.java
- rules-reviewed/eap6/java-ee/seam/tests/data/src/EntityKeyManager.java
- rules-reviewed/eap6/java-ee/seam/tests/data/src/Game.java
- rules-reviewed/eap6/java-ee/seam/tests/data/src/HotelBookingAction.java
- rules-reviewed/eap6/java-ee/seam/tests/data/src/LoginTest.java
- rules-reviewed/eap6/java-ee/seam/tests/data/src/Main.java
- rules-reviewed/eap6/java-ee/seam/tests/data/src/MessageManagerBean.java
- rules-reviewed/eap6/java-ee/seam/tests/data/src/PaymentHome.java
- rules-reviewed/eap6/java-ee/seam/tests/data/src/ShipAction.java
- rules-reviewed/eap6/java-ee/seam/tests/data/src/TestAuthenticator.java
- rules-reviewed/eap6/java-ee/seam/tests/data/src/TestPaymentProcessor.java
- rules-reviewed/eap6/java-ee/seam/tests/data/src/TransactionStatus.java
- rules-reviewed/eap6/java-ee/seam/tests/data/src/WikiUrlRewriteFilter.java
- rules-reviewed/eap6/java-ee/seam/tests/seam-java.windup.test.xml
https://issues.jboss.org/browse/WINDUPRULE-266
> WINDUPRULE-266: new Seam API rules

- rules-reviewed/openshift/local-storage.windup.xml
- rules-reviewed/openshift/logging.windup.xml
- rules-reviewed/openshift/session.windup.xml
- rules-reviewed/openshift/tests/local-storage.windup.test.xml
- rules-reviewed/openshift/tests/logging.windup.test.xml
https://issues.jboss.org/browse/WINDUPRULE-278
I haven't included the following 2 changes for javaclass references:
- https://github.com/Maarc/windup-rulesets/commit/34e22f864ec30eeed35c67606da77f17005cd9a9#diff-68179b4994e8c1c844d59163c749a893L193
- https://github.com/Maarc/windup-rulesets/commit/34e22f864ec30eeed35c67606da77f17005cd9a9#diff-096466b775ea2df36893bdce01c54584L23
Does he have some reasoning for them?
> WINDUPRULE-278: Fixing cloud readiness rules

- rules-reviewed/openshift/logging.windup.xml
- rules-reviewed/openshift/tests/data/Logging.java
- rules-reviewed/openshift/tests/logging.windup.test.xml
Changes after feedbacks from the field that conditions for SLF4J and Apache Commons Logging generate too much noise in the report.
> WINDUPRULE-273: removing SLF4J and Apache Commons Logging

- rules-reviewed/openshift/local-storage.windup.xml
- rules-reviewed/openshift/tests/data/LocalFileUsage.java
- rules-reviewed/openshift/tests/local-storage.windup.test.xml
- Enhancement for finding absolute Windows path so now the rule fires when:
1. Properties file has a path definition (e.g. `: 'C:/`)
1. String path is used to set a variable in Java (e.g. `= "C:/`)
2. String path is used as argument for a method/constructor (e.g. `("C:/`)
- Fix bug about the escape in the `extensions`' pattern
- Update tests accordingly
> WINDUPRULE-274: enhanced Windows path identification and bug fix

- rules-reviewed/technology-usage/ejb-technology-usage.windup.xml
- rules-reviewed/technology-usage/tests/data/ejb/SimpleQueueMDB.java
- rules-reviewed/technology-usage/tests/data/ejb/SimpleStateful.java
- rules-reviewed/technology-usage/tests/data/ejb/SimpleStateless.java
- rules-reviewed/technology-usage/tests/data/ejb/SimpleTopicMDB.java
- rules-reviewed/technology-usage/tests/data/ejb/ejb-jar.xml
- rules-reviewed/technology-usage/tests/data/ejb/jboss-ejb3.xml
- rules-reviewed/technology-usage/tests/ejb-technology-usage.windup.test.xml
Depends on windup/windup#1173
[WINDUPRULE-289](https://issues.jboss.org/browse/WINDUPRULE-289) requests to identify `Managed Beans (CDI)` but here the rule searches for `Entity Bean` just like what has been done in the dynamic EJB report.
> WINDUPRULE-289 Statistics Rules: Connect:EJB/CDI

- rules-reviewed/technology-usage/mvc-technology-usage.windup.xml
- rules-reviewed/technology-usage/mvc.windup.xml
- rules-reviewed/technology-usage/tests/mvc-technology-usage.windup.test.xml
- rules-reviewed/technology-usage/tests/mvc.windup.test.xml
Depends on windup/windup#1177
With the approach of searching for tags, the rules are quite simple and easy to create.
In this case, it searches for these MVC libraries:
- Spring MVC
- Struts (1 & 2)
- Wicket 
- GWT
The `myproject-1.0-SNAPSHOT.war` is a little bit heavy (7-8 MB) but it has inside 11 jars to test all the 4 frameworks.
> WINDUPRULE-285 Statistics Rules: View:MVC

- rules-reviewed/technology-usage/clustering-technology-usage.windup.xml
- rules-reviewed/technology-usage/clustering.windup.xml
- rules-reviewed/technology-usage/tests/clustering-technology-usage.windup.test.xml
- rules-reviewed/technology-usage/tests/clustering.windup.test.xml
- rules-reviewed/technology-usage/tests/data/clustering/ClusteredExample.java
- rules-reviewed/technology-usage/tests/data/clustering/jboss-ejb3.xml
- rules-reviewed/technology-usage/tests/data/clustering/jboss.xml
- rules-reviewed/technology-usage/tests/data/clustering/web.xml
Create rules to add statistics for the following technologies:
- Web Session
- EJB
JPA should also been taken into account but searching for clustering is not standard JPA but based on the specific framework used (e.g. Hibernate, EclipseLink) so it's not be included in this PR waiting for more details about it.
> WINDUPRULE-293 Statistics Rules: Clustering

- rules-reviewed/eap7/eap6/tests/data/data-ws-security/PWCallback.java
- rules-reviewed/eap7/eap6/tests/data/data-ws-security/SAMLIssuerImpl.java
- rules-reviewed/eap7/eap6/tests/data/data-ws-security/SamlCallbackHandler.java
- rules-reviewed/eap7/eap6/tests/ws-security.windup.test.xml
- rules-reviewed/eap7/eap6/ws-security.windup.xml
There are the 2 rules as from JIRA requested in [WINDUPRULE-301](https://issues.jboss.org/browse/WINDUPRULE-301).
There's also a third rule because i found that [`org.apache.ws.security.saml.ext.AssertionWrapper`](https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.4/html-single/API_Documentation/files/javadoc/org/apache/ws/security/saml/ext/AssertionWrapper.html) has been deleted and, it seems, replaced by [`org.apache.wss4j.common.saml.SamlAssertionWrapper`](https://access.redhat.com/webassets/avalon/d/red-hat-jboss-enterprise-application-platform/7.0.0/javadocs/org/apache/wss4j/common/saml/SamlAssertionWrapper.html) class even if there's no 1:1 relation between the methods in the 2 classes.
@mareknovotny and @emmartins do you think we can have this …
> WINDUPRULE-301 WS-Security Changes in JBoss EAP 7

- rules-reviewed/eap7/eap6/jax-ws.windup.xml
- rules-reviewed/eap7/eap6/tests/data/data-jax-ws/HelloWorldImplService.java
- rules-reviewed/eap7/eap6/tests/data/data-jax-ws/RestaurantServiceATService.java
- rules-reviewed/eap7/eap6/tests/jax-ws.windup.test.xml
The issue to address is:
"_Containers must use JAX-WS 2.2 style constructors, using the WebServiceFeature class, to build clients that are injected into web service references. This means that user provided service classes injected by the container must implement JAX-WS 2.2 or later._"
so the rule checks for classes that extends [javax.xml.ws.Service](http://docs.oracle.com/javaee/7/api/javax/xml/ws/Service.html) (in Java EE 7) that has not a constructor with [javax.xml.ws.WebServiceFeature](http://docs.oracle.com/javaee/7/api/javax/xml/ws/WebServiceFeature.html) as last input parameter.
To test the rule, there are 2 classes:
- `HelloWorldImplService` already has the right method with `WebServiceFeature` parameter and so this class should not fire the rule
- `RestaurantServiceATService` …
> WINDUPRULE-302 JAX-WS 2.2 Requirements for WebServiceRef

- rules-reviewed/eap7/eap6/resteasy.windup.xml
- rules-reviewed/eap7/eap6/tests/data/data-resteasy/YamlResource.java
- rules-reviewed/eap7/eap6/tests/resteasy.windup.test.xml
https://issues.jboss.org/browse/WINDUPRULE-307
> WINDUPRULE-314, WINDUPRULE--315,WINDUPRULE-316 Resteasy new rules

- rules-reviewed/eap7/eap6/resteasy.windup.xml
- rules-reviewed/eap7/eap6/tests/data/data-resteasy/YamlResource.java
- rules-reviewed/eap7/eap6/tests/resteasy.windup.test.xml
* WINDUPRULE-314: adding rule for Resteasy Yaml provider
* WINDUPRULE-316: adding rule for Resteasy Serializable Provider
* WINDUPRULE-315: added new rule for default charset in text response
* WINDUPRULE-307: fixes after review
(cherry picked from commit b15ba2c3dcda819d180d0e5bd52cd9534e7f5a43)
> WINDUPRULE-314, WINDUPRULE--315,WINDUPRULE-316 Resteasy new rules (#282)

- rules-reviewed/eap7/eap5/jboss-eap5-7-xml.windup.xml
- classification's title has been changed consistently w/ the hint's title
- let tags only for hint to avoid duplication
- moved the link from the classification the the hint to have them all in the same place
> WINDUPRULE-335 Jboss security configuration descriptor

- rules-reviewed/eap7/eap4and5/jboss-eap4and5to6and7-xml.windup.xml
- rules-reviewed/eap7/eap4and5/tests/data/xml/jboss-beans.xml
- rules-reviewed/eap7/eap4and5/tests/jboss-eap4and5to6and7-xml.windup.test.xml
- fixed typo `beans` in `<where>` parameter for `jboss-beans.xml` file name
- rule `jboss-eap4and5to6and7-xml-02000` search only for MBean since it's the only way to define  the`BarrierController` service
- rule `jboss-eap4and5to6and7-xml-03000` searches w/ different patterns based on the file type
- rule `jboss-eap4and5to6and7-xml-06000` searches only for MBean since it's the only way to define  the `NamingAlias` service as documented in the link to the official documentation added to the `<hint>`
- rule `jboss-eap4and5to6and7-xml-07000` searches only for MBean since it's the only way to define  the `JaasSecurityManagerService` service as documented in the link to the official documentation added to the `<hint>`
- added `jboss-beans.xml` test file and accordingly changed the expected …
> WINDUPRULE-339 jboss-beans.xml not detected

- rules-reviewed/eap7/eap6/hsearch.windup.groovy
- rules-reviewed/eap7/eap6/hsearch.windup.xml
- rules-reviewed/eap7/eap6/tests/data/data-hsearch/Book.java
- rules-reviewed/eap7/eap6/tests/hsearch.windup.test.xml
The new rules searches for `DateBridge` and `CalendarBridge` annotations without the `encoding` attribute
> WINDUPRULE-152 issue with hsearch-00116 conditions

- pom.xml
Added the Sonatype snapshot repository so that, during a new rule creation, a contributor hasn't got to clone and compile any other Windup project.
> WINDUP-2000 Adding Sonatype snapshot repository

- pom.xml
https://issues.jboss.org/browse/WINDUP-2266
To test this PR:
1. clone ruleset project
2. (optional) put demo rules to validate
3. run `mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=demo clean surefire-report:report`
4. check that the report looks bad (without and style and image)
5. apply the changes from this PR
6. run the same command again and, hopefully, the report will be good
> WINDUP-2266 Fix surefire report CSS and images

- rules-reviewed/technology-usage/connect.windup.xml
- rules-reviewed/technology-usage/database.windup.xml
Added links to existing connect.windup.xml and database.windup.xml rules
All database rules had the links added
Only messaging technologies within the connect.windup.xml have had the links added.
No changes to database.windup.test.xml nor connect.windup.test.xml as it is not possible to test for 'links-exists'.
Nor is it possible to specify which order a links will appear in the issue body, so in my testing the EAP7 link appeared first on the issue Report even though the EAP6 link is first in link within the rule.
> WINDUPRULE-359 - Add hint when datasource / jms have been detected

- rules-reviewed/eap7/eap71/hibernate51-53.windup.xml
- rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/pom.xml
- rules-reviewed/eap7/eap71/tests/hibernate51-53.windup.test.xml
dependent on https://github.com/windup/windup/pull/1348
This PR includes solutions for both WINDUPRULE-377 and WINDUPRULE-378 - they are very similar and can both be solved in the same rule by parameterizing it and passing in the artifactIds we wish to search for in each case: 
hibernate-java8 for WINDUPRULE-377, 
hibernate-entitymanager for WINDUPRULE-378
> WINDUPRULE-377: hibernate 5.1-5.3 migration, hibernate-java8 in pom.xml

- rules-reviewed/eap7/eap71/hibernate51-53.windup.xml
- rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate515300700.java
- rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate515300701.java
- rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate515300702.java
- rules-reviewed/eap7/eap71/tests/hibernate51-53.windup.test.xml
https://issues.jboss.org/browse/WINDUPRULE-383
I created rules `hibernate51-53-00701` and `hibernate51-53-00702` because using a parameter for the implemented classes (`SecondLevelCacheStatistics` and  `NaturalIdCacheStatistics`) didn't work.
> WINDUPRULE-383 SecondLevelCacheStatistics and NaturalIdCacheStatistics deprecated methods

- rules-reviewed/eap7/eap71/hibernate51-53.windup.xml
- rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate5153-01000-persistence-eclipselink.xml
- rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate5153-01000-persistence-empty-provider-default-schema.xml
- rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate5153-01000-persistence-empty-provider.xml
- rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate5153-01000-persistence-without-provider-default-catalog.xml
- rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate5153-01000-persistence-without-provider.xml
- rules-reviewed/eap7/eap71/tests/hibernate51-53.windup.test.xml
Fix for [WINDUPRULE-386](https://issues.jboss.org/browse/WINDUPRULE-386?focusedCommentId=13708852&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13708852)
Added a test file [Hibernate5153-01000-persistence-eclipselink.xml](https://github.com/windup/windup-rulesets/compare/master...mrizzi:WINDUPRULE-386?expand=1#diff-0302e37fd2b734f35a1a0560d4f42609) that made the test [hibernate51-53-01000-test](https://github.com/windup/windup-rulesets/blob/master/rules-reviewed/eap7/eap71/tests/hibernate51-53.windup.test.xml#L225) failing and then applied the fix to the rule.
> WINDUPRULE-386 Fix the case when Hibernate is not used

- rules-reviewed/camel3/camel2/tests/data/xml-renamed-components/pom.xml
- rules-reviewed/camel3/camel2/tests/xml-renamed-components.windup.test.xml
- rules-reviewed/camel3/camel2/xml-renamed-components.windup.xml
https://issues.jboss.org/browse/WINDUPRULE-409
Tested executing `$ mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=xml-renamed-components clean surefire-report:report`
> WINDUPRULE-409 camel-http4 renamed

- rules-reviewed/camel3/camel2/java-multiple-camelcontexts-per-application-not-supported.windup.xml
- rules-reviewed/camel3/camel2/tests/data/java-multiple-camelcontexts-per-application-not-supported/Removed.java
- rules-reviewed/camel3/camel2/tests/java-multiple-camelcontexts-per-application-not-supported.windup.test.xml
https://issues.jboss.org/browse/WINDUPRULE-393
To run the validation test execute:
`$ mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=java-multiple-camelcontexts-per-application-not-supported clean surefire-report:report`
> WINDUPRULE-393 'context' attribute removed

- rules-reviewed/camel3/camel2/tests/data/xml-removed-components/pom.xml
- rules-reviewed/camel3/camel2/tests/xml-removed-components.windup.test.xml
- rules-reviewed/camel3/camel2/xml-removed-components.windup.xml
https://issues.jboss.org/browse/WINDUPRULE-408
Tested running `$ mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=xml-removed-components clean surefire-report:report`
> WINDUPRULE-408 camel-linkedin removed

- rules-reviewed/camel3/camel2/xml-removed-components.windup.xml
- rules-reviewed/camel3/camel2/xml-renamed-components.windup.xml
Reviewing https://github.com/windup/windup-rulesets/pull/389 i figured out that some rules are missing the link to the Camel 3 Migration guide so i created this PR to fix it.
@johnpoth in https://camel.apache.org/manual/latest/camel-3-migration-guide.html#_removed_components `camel-linkedin` is not mentioned: do you think it's worth changing the Camel 3 Migration Guide to include it?
> WINDUPRULE-391 Add some missing links

- rules-reviewed/camel3/camel2/java-multiple-camelcontexts-per-application-not-supported.windup.xml
- rules-reviewed/camel3/camel2/tests/data/java-multiple-camelcontexts-per-application-not-supported/ContextRoute.java
- rules-reviewed/camel3/camel2/tests/java-multiple-camelcontexts-per-application-not-supported.windup.test.xml
https://issues.redhat.com/browse/WINDUPRULE-422
Thanks !
cc @mrizzi
> WINDUPRULE-422 @ContextName and @ContextNames have been removed

- rules-reviewed/eap7/eap72/maven-artemis-jms-client.rhamt.xml
- rules-reviewed/eap7/eap72/tests/data/data-maven-artemis-jms-client/pom.xml
- rules-reviewed/eap7/eap72/tests/maven-artemis-jms-client.rhamt.test.xml
Issue: https://issues.jboss.org/browse/WINDUPRULE-404
> WINDUPRULE-404: eap 7.3 maven-artemis-jms-client rules

- rules-reviewed/eap7/eap72/singleton-sessionbean.rhamt.groovy
- rules-reviewed/eap7/eap72/singleton-sessionbean.rhamt.xml
- rules-reviewed/eap7/eap72/tests/data/singleton-sessionbean/AnotherCounter.java
- rules-reviewed/eap7/eap72/tests/data/singleton-sessionbean/Counter.java
- rules-reviewed/eap7/eap72/tests/data/singleton-sessionbean/SingletonBean.java
- rules-reviewed/eap7/eap72/tests/data/singleton-sessionbean/SingletonNoSessionBeanBean.java
- rules-reviewed/eap7/eap72/tests/data/singleton-sessionbean/ejb-jar.xml
- rules-reviewed/eap7/eap72/tests/singleton-sessionbean.rhamt.test.xml
https://issues.redhat.com/browse/WINDUPRULE-403
Hi @emmartins, in the end it has been quicker to create the rule, i hope you don't mind.
I put in the message, the text your provides in Jira's description and the link has the `FIXME` placeholders.
I also added another test class (other than the one provided in Jira) to have a class "fixed" that has not to fire the rule.
Could you please review the message and provide links? And obviously comment whatever else you want (rule file names, mandatory category, etc)
> WINDUPRULE-403 SessionBean interface removed

- rules-reviewed/camel3/camel2/tests/data/xml-renamed-components/pom.xml
- rules-reviewed/camel3/camel2/tests/xml-renamed-components.windup.test.xml
- rules-reviewed/camel3/camel2/xml-renamed-components.windup.xml
https://issues.redhat.com/browse/WINDUPRULE-415
Tested executing $ mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=xml-renamed-components clean surefire-report:report
Thanks !
> WINDUPRULE-415 camel-mongodb3 has been renamed

- rules-reviewed/camel3/camel2/tests/data/xml-moved-components/Attacher.java
- rules-reviewed/camel3/camel2/tests/data/xml-moved-components/RouteBuilder.java
- rules-reviewed/camel3/camel2/tests/data/xml-moved-components/blueprint.xml
- rules-reviewed/camel3/camel2/tests/data/xml-moved-components/camel-rest-dsl-blueprint.xml
- rules-reviewed/camel3/camel2/tests/data/xml-moved-components/camel-rest-dsl-context.xml
- rules-reviewed/camel3/camel2/tests/data/xml-moved-components/context.xml
- rules-reviewed/camel3/camel2/tests/xml-moved-components.windup.test.xml
- rules-reviewed/camel3/camel2/xml-moved-components.windup.xml
https://issues.redhat.com/browse/WINDUPRULE-432 - `camel-zip-deflater` 
https://issues.redhat.com/browse/WINDUPRULE-433  `camel-attachements` 
https://issues.redhat.com/browse/WINDUPRULE-435  `camel-dataformat` 
https://issues.redhat.com/browse/WINDUPRULE-436  `camel-language` 
https://issues.redhat.com/browse/WINDUPRULE-437  `camel-rest` 
https://issues.redhat.com/browse/WINDUPRULE-438 `camel-xpath`
> [WINDUPRULE-432,433,435,436,437,438] - camel components moved out of camel-core

- rules-reviewed/camel3/camel2/java-generic-information.windup.xml
- rules-reviewed/camel3/camel2/tests/data/java-generic-information/MyAggregationStrategy.java
- rules-reviewed/camel3/camel2/tests/data/java-generic-information/RouteBuilder.java
- rules-reviewed/camel3/camel2/tests/data/xml-generic-information/context.xml
- rules-reviewed/camel3/camel2/tests/data/xml-moved-components/RouteBuilder.java
- rules-reviewed/camel3/camel2/tests/data/xml-moved-components/blueprint.xml
- rules-reviewed/camel3/camel2/tests/java-generic-information.windup.test.xml
- rules-reviewed/camel3/camel2/tests/xml-generic-information.windup.test.xml
- rules-reviewed/camel3/camel2/tests/xml-moved-components.windup.test.xml
- rules-reviewed/camel3/camel2/xml-generic-information.windup.xml
- rules-reviewed/camel3/camel2/xml-moved-components.windup.xml
https://issues.redhat.com/browse/WINDUPRULE-440
https://issues.redhat.com/browse/WINDUPRULE-443
https://issues.redhat.com/browse/WINDUPRULE-444
https://issues.redhat.com/browse/WINDUPRULE-446
https://issues.redhat.com/browse/WINDUPRULE-447
https://issues.redhat.com/browse/WINDUPRULE-448
https://issues.redhat.com/browse/WINDUPRULE-450
https://issues.redhat.com/browse/WINDUPRULE-451
https://issues.redhat.com/browse/WINDUPRULE-452
https://issues.redhat.com/browse/WINDUPRULE-453
https://issues.redhat.com/browse/WINDUPRULE-454
https://issues.redhat.com/browse/WINDUPRULE-455
https://issues.redhat.com/browse/WINDUPRULE-456
> [WINDUPRULE-440,443,444,446,447,448,450,451,452,453,454,455,456] Add rules for java generic information chapter

- rules-reviewed/camel3/camel2/tests/data/xml-removed-components/AwsBlueprintTest.xml
- rules-reviewed/camel3/camel2/tests/data/xml-removed-components/AwsSpringNegativeTest.xml
- rules-reviewed/camel3/camel2/tests/data/xml-removed-components/AwsSpringTest.xml
- rules-reviewed/camel3/camel2/tests/data/xml-removed-components/CwComponentTest.java
- rules-reviewed/camel3/camel2/tests/data/xml-removed-components/pom.xml
- rules-reviewed/camel3/camel2/tests/xml-removed-components.windup.test.xml
- rules-reviewed/camel3/camel2/xml-removed-components.windup.xml
https://issues.redhat.com/browse/WINDUPRULE-425
Thanks !
To run tests: `mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=xml-removed-components clean surefire-report:report`
> WINDUPRULE-425 camel-aws has been split up into multiple components

- rules-reviewed/technology-usage/embedded-framework.windup.xml
- rules-reviewed/technology-usage/tests/embedded-framework.windup.test.xml
https://issues.redhat.com/browse/WINDUPRULE-587
* changed rule position to work effectively
* fixed the `has-classification` pattern
* added `DI` to the pattern (`Spring DI` added in https://github.com/windup/windup-rulesets/pull/431)
* fixed the message in the test to have the right rule ID
This can be tested with `mvn -DrunTestsMatching=embedded-framework clean test`
Screenshot with fixed report (compared to the [wrong ones in Jira](https://issues.redhat.com/browse/WINDUPRULE-587?focusedCommentId=14064009&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14064009))
> WINDUPRULE-587 Spring JAR classification fix

- rules-reviewed/camel3/camel2/tests/data/xml-moved-components/application0/MyRouteBuilder.java
- rules-reviewed/camel3/camel2/tests/xml-moved-components.windup.test.xml
- rules-reviewed/camel3/camel2/xml-moved-components.windup.groovy
- rules-reviewed/camel3/camel2/xml-moved-components.windup.xml
Refactor rules for component moved out of camel-core. Because of new dependencies not being mandatory, current rule throws only one hint with list of components that were used in to project with message that components could be moved. 
Tests can be run with ` mvn -DrunTestsMatching=xml-moved-components clean test`
> WINDUPRULE-603

- rules-reviewed/camel3/camel2/xml-moved-components.windup.xml
https://issues.redhat.com/browse/WINDUPRULE-604
to run tests: `mvn -DrunTestsMatching=xml-moved-components clean test`
Thanks!
> WINDUPRULE-604 fix xml-moved-components-00014

- rules-reviewed/camel3/camel2/tests/data/xml-removed-components/pom.xml
- rules-reviewed/camel3/camel2/tests/data/xml-renamed-components/pom.xml
- rules-reviewed/camel3/camel2/tests/xml-removed-components.windup.test.xml
- rules-reviewed/camel3/camel2/tests/xml-renamed-components.windup.test.xml
- rules-reviewed/camel3/camel2/xml-removed-components.windup.groovy
- rules-reviewed/camel3/camel2/xml-removed-components.windup.xml
- rules-reviewed/camel3/camel2/xml-renamed-components.windup.xml
https://issues.redhat.com/browse/WINDUPRULE-601
To run tests:
`mvn -DrunTestsMatching=xml-removed-components clean test` &&
`mvn -DrunTestsMatching=xml-renamed-components clean test`
Thanks !
> Winduprule 601

- rules-reviewed/camel3/camel2/java-generic-information.windup.xml
- rules-reviewed/camel3/camel2/tests/java-generic-information.windup.test.xml
- rules-reviewed/camel3/camel2/xml-moved-components.windup.xml
https://issues.redhat.com/browse/WINDUPRULE-610
To run tests:  `mvn -DrunTestsMatching=xml-moved-components clean test -nsu` && `mvn -DrunTestsMatching=java-generic-information clean test -nsu`
I've simply removed the check for `camel-support` and `camel-base` as it's not needed.
I've also noticed, while testing, that java-generic-information-00003 is a duplicate of xml-moved-components-00012 so I removed it. cc @jonathanvila @mmelko 
Thanks!
> Winduprule 610

- rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml
- rules-reviewed/eap6/jboss-eap5/jboss-eap5-xml.windup.xml
- rules-reviewed/eap7/eap4and5/jboss-eap4and5to6and7-xml.windup.xml
- rules-reviewed/eap7/eap5and6/jboss-eap5and6to7-xml.windup.xml
https://issues.redhat.com/browse/WINDUPRULE-644
EAP 4.x documentation is no longer supported. Broken links have been removed from rulesets.
> Removed broken links to EAP 4.x documentation

- rules-reviewed/quarkus/springboot/springboot-jmx-to-quarkus.windup.xml
https://issues.redhat.com/browse/WINDUPRULE-656
> WINDUPRULE-656: Spring Boot JMX to Quarkus rule - alter hint to mention hotspot compilation support

- pom.xml
https://issues.redhat.com/browse/WINDUPRULE-665
Temporary disabling the test since a lot of PRs for rules are coming and without a working solution in #494, we have to disable this check to have a more stable build to know if the tests are fine with each PR and each nightly build accepting the risk of having some broken link.
> WINDUPRULE-665 Disable links test temporary

- rules-reviewed/camel3/camel2/tests/xml-moved-components.windup.test.xml
- rules-reviewed/camel3/camel2/xml-moved-components.windup.groovy
https://issues.redhat.com/browse/WINDUP-2937
After having changed the Groovy-all extensions version in https://github.com/windup/windup/pull/1403, the order of the Camel components in the hint's message changed.
So the PR introduces sorting of values to have them always in the same order and hence safely testable.
> WINDUP-2937 Added sorting to have a deterministic ordering in hint's message

- rules-reviewed/quarkus1/quarkus1-11/quarkus1-12-mailer.windup.xml
- rules-reviewed/quarkus1/quarkus1-11/tests/data/MailerResource.java
- rules-reviewed/quarkus1/quarkus1-11/tests/quarkus1-12-mailer.windup.test.xml
This PR is incomplete. It has been created to illustrate a problem that WINDUP has identifying a method call. the rule is trying to identify the MailTemplateInstance.send() method. It has revealed a generic problem with WINDUP in that it can't deal with the fluent API.
The message text should contain void (in diagonal brackets) however that seems to be incompatible with writing a rule in XML so the final version of this rule may have to be groovy.
> WINDUPRULE-717 Quarkus Release 1.12 - Mailer

- rules-reviewed/eapxp/thorntail/replace_thorntail_boms.mta.xml
- rules-reviewed/eapxp/thorntail/tests/data/data-replace_thorntail_boms/pom.xml
- rules-reviewed/eapxp/thorntail/tests/replace_thorntail_boms.mta.test.xml
Apply again the changes from https://github.com/windup/windup-rulesets/pull/549 (reverted in https://github.com/windup/windup-rulesets/pull/550) for https://issues.redhat.com/browse/WINDUPRULE-738
> [WINDUPRULE-738] (thorntail -> eap xp2+) replace thorntail boms

- rules-reviewed/openjdk11/openjdk8/java-removals.windup.xml
- rules-reviewed/openjdk11/openjdk8/tests/data/java-removals/ThreadStop.java
- rules-reviewed/openjdk11/openjdk8/tests/java-removals.windup.test.xml
First attempt at a rule for the transition from OpenJDK 8 to 11.
See: https://issues.redhat.com/browse/WINDUPRULE-754
Rule was successfully tested locally:
~~~~
$ ${RHAMT_HOME}/bin/mta-cli --sourceMode --input \
rules-reviewed/openjdk11/openjdk8/tests/data --output /tmp/oj11-report \
--target openjdk:11
~~~~~
but testing via Maven failed with unrelated errors
~~~~
$ mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=java-generic clean surefire-report:report 
org.jboss.arquillian.container.spi.client.container.DeploymentException: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find org.jboss.windup.graph:windup-graph-impl:jar:5.1.5-SNAPSHOT in https://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update …
> WINDUPRULE-754 java.lang.Thread.stop(java.lang.Throwable) has been removed

- rules-reviewed/openjdk11/openjdk8/removed-javaee-modules.windup.xml
- rules-reviewed/openjdk11/openjdk8/tests/data/removed-javaee-modules/CompleteDukeApplication.java
- rules-reviewed/openjdk11/openjdk8/tests/removed-javaee-modules.windup.test.xml
Rule for identifying the `java.activation` module that has been removed in OpenJDK-11
> WINDUPRULE-772 OpenJDK8 to OpenJDK11 java.activation module removed

- rules-reviewed/openjdk11/openjdk11.windup.technologytransformer.xml
Building a CLI with this change, makes the CLI executed with `--listTargetTechnologies` command to print:
```shell
Available target technologies:
camel
cloud-readiness
drools
eap
eap6
eap7
eapxp
fsw
fuse
generate-quarkus
hibernate
hibernate-search
jakarta-ee
java-ee
jbpm
linux
openjdk
openjdk11
quarkus
quarkus1
resteasy
rhr
```
where `openjdk11` is available.
> Added 'openjdk11' shortcut

- pom.xml
During the release, there was an ongoing outage on maven.repository.redhat.com that generated this failure:
```shell
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site (download-css) on project windup-rulesets: SiteToolException: The site descriptor cannot be resolved from the repository: ArtifactResolutionException: Unable to locate site descriptor: Could not transfer artifact org.jboss:jboss-parent:xml:site_en:22 from/to redhat-ga-repository (https://maven.repository.redhat.com/ga/): Failed to transfer file: https://maven.repository.redhat.com/ga/org/jboss/jboss-parent/22/jboss-parent-22-site_en.xml. Return code is: 500 , ReasonPhrase:Internal Server Error.
```
Since tests were skipped, also the `download-css`, which is bounded to `test` phase, has been …
> Skip 'download-css' when not testing

- .github/workflows/pr_build_jdk11.yml
- pom.xml
- src/test/java/org/jboss/windup/rules/tests/WindupRulesTest.java
See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3204).
> [WINDUP-3204] Migrate to jdk11

- rules-reviewed/openliberty/websphere/liberty-websphere-unavailable-technologies.windup.xml
This is a fix to correct a duplicate bullet point in the body of a message and replace 2 broken links.
I have added the new links as true rule link elements rather than hyperlinks embedded within the message element.
> WINDUP-3277 OpenLiberty Dynamic Cache links fix

- rules-reviewed/quarkus/springboot/springboot-actuator-to-quarkus.windup.xml
- rules-reviewed/quarkus/springboot/tests/data/springboot-actuator/application.properties
- rules-reviewed/quarkus/springboot/tests/springboot-actuator-to-quarkus.windup.test.xml
This is another properties based change that originates from https://github.com/RedHat-Middleware-Workshops/spring-to-quarkus-todo#migrate-data-source-properties. Please review that link to verify the change advised by the rule firing is appropriate.
> WINDUPRULE-829 SB2Quarkus map health endpoint

- rules-reviewed/openjdk11/openjdk8/java-removals.windup.xml
- rules-reviewed/openjdk11/openjdk8/tests/data/java-removals/AWTSecurityManagement.java
- rules-reviewed/openjdk11/openjdk8/tests/java-removals.windup.test.xml
https://issues.redhat.com/browse/WINDUPRULE-798
> WINDUPRULE-798: AWT SecurityManager methods removed rule

- rules-reviewed/openjdk11/openjdk8/java-removals.windup.xml
- rules-reviewed/openjdk11/openjdk8/tests/data/java-removals/AWTSecurityManagement.java
- rules-reviewed/openjdk11/openjdk8/tests/data/java-removals/ThreadStop.java
- rules-reviewed/openjdk11/openjdk8/tests/java-removals.windup.test.xml
See [https://issues.redhat.com/browse/WINDUPRULE-799](https://issues.redhat.com/browse/WINDUPRULE-799) and [https://issues.redhat.com/browse/WINDUPRULE-797](https://issues.redhat.com/browse/WINDUPRULE-797).
> [WINDUPRULE-[797, 799]] Implement rules for checkMemberAccess method in SecurityManager and runFinalizersOnExit methods

- rules-reviewed/os/windows/os-specific.windup.xml
- rules-reviewed/os/windows/tests/os-specific.windup.test.xml
Some Java projects can embed DLL files for native Windows calls.
This rule checks if there are *.dll files in the project
> Add DLL rule

- rules-reviewed/openjdk11/openjdk8/java-removals.windup.xml
- rules-reviewed/openjdk11/openjdk8/tests/data/java-removals/ComponentGetPeer.java
- rules-reviewed/openjdk11/openjdk8/tests/java-removals.windup.test.xml
@jmle Can I ask you to investigate an issue for me?
The Componet.getPeer() aspect of this rule is not firing even though I have rebuild the CLI after the PR to add the Component.class to the removed classes jar.
If I run a custom rule from the 5.3.0 CLI  containing exactly the same logic. It does fire.
> WINDUPRULE-788 - ComponentPeer removal rules

- rules-reviewed/openrewrite/jakarta/javax/imports/rewrite.yml
https://issues.redhat.com/browse/WINDUP-3295
The openrewrite recipe contained in this PR requires https://github.com/windup/windup-distribution/pull/84 if it is to be used via the mta-cli
> WINDUP-3295: add dependency migration to javax-jakarta recipe

- rules-reviewed/azure/azure-password.windup.xml
- rules-reviewed/azure/tests/azure-password.windup.test.xml
- rules-reviewed/azure/tests/data/azure-password/h2-ds.xml
- rules-reviewed/azure/tests/data/azure-password/ora-ds.xml
- rules-reviewed/azure/tests/data/azure-password/pgsql-ds.xml
Extend the detection of plain-text passwords from #705 to XML configuration files
> Azure - Detect plain-text passwords in XML config files

- .editorconfig
Adding a basic .editorconfig file so the XML rules are all formatted the same with 4 spaces indentation
> Adding a basic .editorconfig file

- rules/rules-reviewed/technology-usage/javase-technology-usage.windup.xml
- rules/rules-reviewed/technology-usage/javase.windup.xml
- rules/rules-reviewed/technology-usage/tests/data/javase/JavaSEExecutor.java
- rules/rules-reviewed/technology-usage/tests/data/javase/JavaSEThread.java
- rules/rules-reviewed/technology-usage/tests/javase-technology-usage.windup.test.xml
This rule detects that an application is using Java SE Thread APIs. This is important to detect when running in an application server or the cloud
> Detects Java SE Threads usage

- rules/rules-reviewed/eap6/weblogic/weblogic.windup.xml
- rules/rules-reviewed/eap7/weblogic/weblogic.windup.xml
@m-brophy - 2 rules needed changing.
As we have rules for Weblogic to EAP6 and WebLogic to EAP7
The former need to be retired. I'll create a separate Jira for that.
> WINDUPRULE-932 Fix broken EAP Logging links in Weblogic to EAP Rules

- rules/rules-reviewed/technology-usage/embedded-framework-technology-usage.windup.xml
- rules/rules-reviewed/technology-usage/javaee-technology-usage.windup.xml
- rules/rules-reviewed/technology-usage/tests/data/javaee/JsonControllerJakarta.java
- rules/rules-reviewed/technology-usage/tests/embedded-framework-technology-usage.windup.test.xml
- rules/rules-reviewed/technology-usage/tests/javaee-technology-usage.windup.test.xml
https://issues.redhat.com/browse/WINDUPRULE-934
- added Jakarta CDI identification rule
- removed duplicated `technology-usage-embedded-framework-05500`
- set CDI in the `Inversion of Control` box
PS: I've tried a lot for having just one rule covering both `javax` and `jakarta` root packages but it never worked as expected (I suspect due to [WINDUP-1324](https://issues.redhat.com/browse/WINDUP-1324).
The sample not-working rule I've tried with was (`hint` is there for the sake of having a quick feedback on reports):
```xml
<rule id="javaee-technology-usage-00019">
<when>
<javaclass references="{ee-flavor}{enterprise}inject.{*}">
<location>IMPORT</location>
</javaclass>
</when>
<perform>
<hint title="found CDI" effort="13">
<message>found CDI in {ee-flavor}{enterprise}</message>
</hint> …
```
> WINDUPRULE-934 Added CDI Jakarta technology-tag

- rules/rules-reviewed/eap8/eap7/jakarta-json-binding.windup.xml
- rules/rules-reviewed/eap8/eap7/tests/data/jakarta-json-binding/JakartaJsonBinding.java
- rules/rules-reviewed/eap8/eap7/tests/jakarta-json-binding.windup.test.xml
See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-910).
> [WINDUPRULE-910] Rule for jakarta json binding

- rules/rules-reviewed/eap8/eap7/hibernate6.windup.xml
https://issues.redhat.com/browse/WINDUP-3692
Analyzing the same set of applications with a CLI built with these rules, the stats report `180.462, hibernate6` while with today CLI snapshot I have `372.737, hibernate6` so it looks like there's an improvement.
> WINDUP-3692 'hibernate6' rules refactoring

- rules/rules-reviewed/eap8/eap7/hibernate-6.2.windup.xml
- rules/rules-reviewed/eap8/eap7/tests/data/hibernate-62/TestClass.java
- rules/rules-reviewed/eap8/eap7/tests/hibernate-6.2.windup.test.xml
See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-954).
> [WINDUPRULE-954] Create ruleset for hibernate 6.2

- rules/rules-reviewed/eap8/eap7/hibernate6.windup.xml
https://issues.redhat.com/browse/WINDUPRULE-966
The PR removes the need for checking the application is using exactly `hibernate` artifact because it would make the rule to not work when
- doing a migration of another framework that relies upon Hibernate, e.g. Quarkus
- doing a migration from another JPA implementation to Hibernate 6
The removal of the version check will let the rule fire also with Hibernate 6 or any framework dependant on it but it's a potential rule exactly meaning "there is not enough detailed information to determine if the task is mandatory"
> WINDUPRULE-966 Removed 'hibernate' dependency conditions

- rules/rules-reviewed/azure/azure-file-system.windup.xml
- rules/rules-reviewed/azure/azure-password.windup.xml
- rules/rules-reviewed/azure/springboot/spring-boot-to-azure-cache.windup.xml
- rules/rules-reviewed/azure/springboot/spring-boot-to-azure-database.windup.xml
- rules/rules-reviewed/azure/springboot/spring-boot-to-azure-eureka.windup.xml
- rules/rules-reviewed/azure/springboot/spring-boot-to-azure-feign.windup.xml
- rules/rules-reviewed/azure/springboot/spring-boot-to-azure-identity-provider.windup.xml
- rules/rules-reviewed/azure/springboot/spring-boot-to-azure-jms-broker.windup.xml
- rules/rules-reviewed/azure/springboot/spring-boot-to-azure-schedule-job.windup.xml
- rules/rules-reviewed/azure/springboot/spring-boot-to-azure-static-content.windup.xml
- rules/rules-reviewed/azure/springboot/spring-boot-to-azure-zipkin.windup.xml
1)  Make rule spring boot rule azure target to azure spring apps
2) Update the doc link to azure spring apps
> Make rule spring boot rule available for spring apps

- rules/rules-reviewed/openjdk7/oraclejdk7/oracle2openjdk.rhamt.xml
- rules/rules-reviewed/openjdk7/oraclejdk7/tests/data/ImageEncoderTest.java
- rules/rules-reviewed/openjdk7/oraclejdk7/tests/oracle2openjdk.rhamt.test.xml
Like the other ruleset in the ruleset without adding an additional classpath to a jar containing the obsolete oracle java classes the rules can actually only pick up the obsolete package in the import statements, rather than in the body of the test data java classes. 
The new rule is consistent with the other rules in the ruleset.    
We would need legal advice about adding those Oracle classes.
But because it is an aging ruleset, and the utility of it is diminishing over time, it is fit for purpose.
> WINDUPRULE-944 obsolete OracleJDK package

- rules/src/test/java/org/jboss/windup/rules/tests/WindupRulesMultipleTests.java
- rules/src/test/java/org/jboss/windup/rules/tests/WindupRulesTest.java
With this change, something like `<testDataPath>data/*</testDataPath>` in a `*.windup.test.xml` file will work, consistently to the experience when running with the Windup CLI with such value for the input path.
Right now there are no tests that uses it and it's done on purpose: this PR just wants to introduce the change testing it doesn't break any of the current tests.
Later on, some new rules will have tests that will leverage this enhancement.
> Enhanced tests to support '/*' syntax for 'testDataPath' tag

- .github/workflows/pr_build_jdk11.yml
To avoid errors like `Non-resolvable import POM: Could not find artifact org.jboss.windup:windup-bom:pom:6.2.4-SNAPSHOT in sonatype-snapshots-repo (https://oss.sonatype.org/content/repositories/snapshots) @ line 85, column 25` in the backport PRs (e.g. https://github.com/windup/windup-rulesets/actions/runs/4891189140/jobs/8731390087?pr=943) also the `WindupRulesLinksTest` needs to wait for the `windup-build` job to build to leverage the cached artifacts
> WindupRulesLinksTest job needs windup-build job

- rules-themed/rules-mta/labels/core.windup.label.xml
- rules-themed/rules-mtr/labels/core.windup.label.xml
- rules/rules-reviewed/technology-usage/tests/javaee-technology-tag.windup.test.xml
- rules/rules-reviewed/technology-usage/tests/web-technology-usage.windup.test.xml
- rules/rules-reviewed/technology-usage/tests/web.windup.test.xml
- rules/rules-reviewed/technology-usage/web-technology-usage.windup.xml
- rules/rules-reviewed/technology-usage/web.windup.xml
See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-978).
> [WINDUPRULE-978] Add new ruleset for web technologies

- rules/rules-reviewed/quarkus/java-ee/javaee-api-to-quarkus.windup.groovy
- rules/rules-reviewed/quarkus/java-ee/javaee-pom-to-quarkus.windup.xml
- rules/rules-reviewed/quarkus/java-ee/jaxrs-to-quarkus.windup.xml
- rules/rules-reviewed/quarkus/java-ee/tests/data/helloworld-rs-migrated/pom.xml
- rules/rules-reviewed/quarkus/java-ee/tests/javaee-api-to-quarkus.windup.test.xml
- rules/rules-reviewed/quarkus/java-ee/tests/jaxrs-to-quarkus.windup.test.xml
- rules/rules-reviewed/quarkus/quarkus3.windup.technologytransformer.xml
https://issues.redhat.com/browse/WINDUPRULE-945
Implementing feedback from https://github.com/windup/jboss-eap-quickstarts/pull/1
> WINDUPRULE-945 quarkus3 alias and other feedback implemented

- rules/rules-reviewed/technology-usage/database.windup.groovy
Alternative implementation for https://github.com/Azure/windup-rulesets/pull/39
When an Azure related targets is selected a further hint is added to the analysis with SPs and Category.
The classification is still there since it's just an information with 0 SP so it doesn't affect the effort involved in migrating.
Sample of analysis without and with a Azure target:
@agoncal WDYT?
> PostgreSQL technology: conditional hint for Azure targets

- rules/rules-reviewed/openjdk11/openjdk8/java-removals.windup.xml
- rules/rules-reviewed/quarkus/springboot/springboot-plugins-to-quarkus.windup.xml
Hi Mark, Can you quickly review this very simple PR please?
> WINDUPRULE-940 correct erroneous effort values

- rules/src/test/java/org/jboss/windup/rules/tests/RuleTest.java
- rules/src/test/java/org/jboss/windup/rules/tests/RuleTestHandler.java
- rules/src/test/java/org/jboss/windup/rules/tests/WindupRulesTest.java
Based on @agoncal's report about rules tests execution:
> Sometimes when you run tests matching a short word (eg. mvn clean test -DrunTestsMatching=web) you end up with several reports under target . Then, to find the appropriate one is quite difficult, You need to browse through all of them. When you open the report, most of the reports are named data, but not all of them.
which is reflected in the next screenshot 
with the changes in this PR, the same tests execution will create this folders structure:
> Refactored test output folder name

- rules/rules-reviewed/eap8/eap7/hibernate-6.2.windup.xml
- rules/rules-reviewed/eap8/eap7/hibernate-search-6.1.windup.xml
- rules/rules-reviewed/eap8/eap7/hibernate-search.windup.xml
- rules/rules-reviewed/eap8/eap7/hibernate6.windup.xml
- rules/rules-reviewed/quarkus/java-ee/cdi-to-quarkus.windup.xml
- rules/rules-reviewed/quarkus/java-ee/dependency-removal-for-quarkus.windup.xml
- rules/rules-reviewed/quarkus/java-ee/javaee-faces-to-quarkus.windup.xml
- rules/rules-reviewed/quarkus/java-ee/javaee-pom-to-quarkus.windup.xml
- rules/rules-reviewed/quarkus/java-ee/jaxrs-to-quarkus.windup.xml
- rules/rules-reviewed/quarkus/java-ee/tests/cdi-to-quarkus.windup.test.xml
- rules/rules-reviewed/quarkus/java-ee/tests/data/application-javaee-api/src/main/java/sample/HelloEJB.java
- rules/rules-reviewed/quarkus/java-ee/tests/data/application-javaee-api/src/main/java/sample/HelloService.java
- rules/rules-reviewed/quarkus/java-ee/tests/data/helloworld-rs-migrated/pom.xml
- rules/rules-reviewed/quarkus/java-ee/tests/data/packaging/without-packaging/pom.xml
- rules/rules-reviewed/quarkus/java-ee/tests/dependency-removal-for-quarkus.windup.test.xml
- rules/rules-reviewed/quarkus/java-ee/tests/javaee-faces-to-quarkus.windup.test.xml
- rules/rules-reviewed/quarkus/java-ee/tests/javaee-pom-to-quarkus.windup.test.xml
- rules/rules-reviewed/quarkus/java-ee/tests/jaxrs-to-quarkus.windup.test.xml
https://issues.redhat.com/browse/WINDUPRULE-1030
kitchensink migration to quarkus 3 windup rules
> Winduprule-1030

- rules/rules-reviewed/openjdk11/openjdk8/java-removals.windup.xml
These are broken links:
- https://hg.openjdk.java.net/openjfx/9-dev/rt/rev/70f6fa01a32c
- https://hg.openjdk.java.net/jdk9/jdk9/jdk/rev/0a0a0986400e#l2.19
- https://hg.openjdk.java.net/jdk8/jdk8/jdk/rev/9078c34437ab
As reported in https://www.mail-archive.com/web-discuss@openjdk.org/msg00008.html: 
> The sources on hg.openjdk.org are severely outdated and the server is only kept around for reference. We have migrated all relevant repositories to GitHub and that is now our preferred hosting solution.
So I've tried to find the same commits in GitHub OpenJDK repositories.
In order to achieve it, I've searched for the OpenJDK's bugs the commits referenced in the broken links above were fixing and, using the bug ID, I've searched the related commits in  OpenJDK's repositories and replaced the …
> Update broken links in OpenJDK rules

- rules/rules-reviewed/quarkus/java-ee/jakarta-api-to-quarkus.windup.groovy
- rules/rules-reviewed/quarkus/java-ee/javaee-api-to-quarkus.windup.groovy
- rules/rules-reviewed/quarkus/java-ee/tests/data/application-jakarta-api/pom.xml
- rules/rules-reviewed/quarkus/java-ee/tests/data/application-jakarta-api/src/main/java/sample/HelloWorld.java
- rules/rules-reviewed/quarkus/java-ee/tests/jakarta-api-to-quarkus.windup.test.xml
- rules/rules-reviewed/quarkus/java-ee/tests/javaee-pom-to-quarkus.windup.test.xml
[WINDUP-1041](https://issues.redhat.com/browse/WINDUPRULE-1041)
> WINDUPRULE-1041 jakarta-api-to-quarkus groovy rules

- rules/rules-reviewed/eap7/eap6/resteasy.windup.xml
- rules/rules-reviewed/eap7/weblogic/weblogic-webservices.windup.xml
https://issues.redhat.com/browse/WINDUPRULE-1049
> WINDUPRULE-1049 fix broken links
