rules/javaee/XmlWebServicesRules.windup.xml
rules/jboss-eap/weblogic/XmlWebLogicRules.windup.xml

Starting small to verify this is the correct approach.

Replace rule variables with more meaningful names - Part 1

---

rules/jboss-eap/log4j/Log4jRules.windup.xml
rules/jboss-eap/log4j/tests/Log4jRulesTest.windup.test.xml
rules/jboss-eap/log4j/tests/data/pom.xml
src/test/java/org/jboss/windup/rules/tests/LineitemExists.java
src/test/java/org/jboss/windup/rules/tests/LineitemExistsHandler.java

first try to satisfy https://issues.jboss.org/browse/WINDUP-65, @lincolnthree or @jsight  please review and let me know your comments ;)

https://issues.jboss.org/browse/WINDUP-65 added project log4j GAV rule

---

rules/jboss-eap/log4j/Log4jRules.windup.xml
rules/jboss-eap/log4j/tests/Log4jRulesTest.windup.test.xml
rules/jboss-eap/log4j/tests/data/log4j.properties
rules/jboss-eap/log4j/tests/data/log4j.xml

additions to log4j rules as requested by Oscar Arribas

WINDUP-65 - adding log4j rules for log4j.properties and log4j.xml files

---

rules/javaee/XmlSpringRules.windup.xml

https://issues.jboss.org/browse/WINDUP-589

WINDUP-589: XPath Not Highlighting Lines Correctly

---

rules-reviewed/jboss-eap/weblogic/tests/data-servicetests/NonCatalogLoggerTest.java
rules-reviewed/jboss-eap/weblogic/tests/data-servicetests/T3ServicesDefLookupTest.java
rules-reviewed/jboss-eap/weblogic/tests/data-servicetests/T3StartupDefTest.java
rules-reviewed/jboss-eap/weblogic/tests/data-webservicetests/AsyncPreCallContextTest.java
rules-reviewed/jboss-eap/weblogic/tests/data-webservicetests/ServiceImplSubclassTest.java
rules-reviewed/jboss-eap/weblogic/tests/data-webservicetests/WebLogicServiceContextTest.java
rules-reviewed/jboss-eap/weblogic/tests/data/TriggerableTest.java
rules-reviewed/jboss-eap/weblogic/tests/data/WebLogicApacheXmlTest.java
rules-reviewed/jboss-eap/weblogic/tests/data/WebLogicJDBCTest.java
rules-reviewed/jboss-eap/weblogic/tests/data/WebLogicStringUtilsTest.java
rules-reviewed/jboss-eap/weblogic/tests/data/WebLogicTransactionTests.java
rules-reviewed/jboss-eap/weblogic/tests/weblogic-services.windup.test.xml
rules-reviewed/jboss-eap/weblogic/tests/weblogic-webservices.windup.test.xml
rules-reviewed/jboss-eap/weblogic/tests/weblogic.windup.test.xml
rules-reviewed/jboss-eap/weblogic/weblogic-services.windup.xml
rules-reviewed/jboss-eap/weblogic/weblogic-webservices.windup.xml
rules-reviewed/jboss-eap/weblogic/weblogic.windup.xml

Some of these are more web-service related than others.

WebLogic "webservices" rules review

---

rules-reviewed/jboss-eap/weblogic/tests/data/weblogic-datasource.xml
rules-reviewed/jboss-eap/weblogic/tests/weblogic.windup.test.xml
rules-reviewed/jboss-eap/weblogic/weblogic.windup.xml

missing piece from Migration guide

new rule for Oracle FCF and Weblogic

---

rules-reviewed/hibernate/hibernate-xml.windup.xml
rules-reviewed/hibernate/hibernate.windup.xml
rules-reviewed/jboss-eap/weblogic/weblogic-xml-descriptors.windup.xml
rules-reviewed/jboss-eap/weblogic/weblogic.windup.xml

previous links pointed to private articles

Updated links to public articles

---

rules-reviewed/jboss-eap/weblogic/weblogic-jms.windup.xml
rules-reviewed/jboss-eap/weblogic/weblogic-services.windup.xml
rules-reviewed/jboss-eap/weblogic/weblogic-webapp.windup.xml
rules-reviewed/jboss-eap/weblogic/weblogic-webservices.windup.xml
rules-reviewed/jboss-eap/weblogic/weblogic-xml-descriptors.windup.xml
rules-reviewed/jboss-eap/weblogic/weblogic.windup.xml
rules-reviewed/jboss-eap/websphere/websphere-mq.windup.xml
rules-reviewed/jboss-eap/websphere/websphere-mqe.windup.xml
rules-reviewed/jboss-eap/websphere/websphere-xml.windup.xml

WINDUP-694  Add tags to rules

---

rules-reviewed/jboss-eap/websphere/websphere-xml.windup.xml

Also, cleaned up the File rules for websphere to improve the point handling.

Added title to the 'file' hints

---

rules-reviewed/jboss-eap/uncategorized/environment-dependent-catchall.windup.xml
rules-reviewed/jboss-eap/uncategorized/tests/data/MyClass.java
rules-reviewed/jboss-eap/uncategorized/tests/environment-dependent-catchall.windup.test.xml
rules/uncategorized/Rules.windup.xml

I removed from rules/uncategorized of those that were migrated. I didn't do all of them because migrating this was not yet decided. So this is more like a bonus for this sprint in which I migrated those that I subjectively think have the biggest added value.

QA'd some of the uncategorised rules

---

rules-reviewed/jboss-eap/websphere/websphere-xml.windup.xml

result from discussion on https://tree.taiga.io/project/lincolnthree-jboss-migration/task/202

tuned task #202 for IBM binding XML rules

---

rules-reviewed/jboss-eap/weblogic/weblogic.windup.xml

WINDUPRULE-91 differentiate hint title for weblogic-05000 and

---

rules-reviewed/filemappings/default-package-to-organization-names.windup.xml
rules-reviewed/jboss-eap/weblogic/weblogic-ignore-references.windup.xml
rules-reviewed/jboss-eap/weblogic/weblogic.windup.xml
rules-reviewed/jboss-eap/websphere/tests/websphere-xml.windup.test.xml
rules-reviewed/jboss-eap/websphere/websphere-ignore-references.windup.xml
rules-reviewed/jboss-eap/websphere/websphere-xml.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-94

WINDUPRULE-94: Fix WebSphere and WebLogic spelling

---

pom.xml
rules-reviewed/jboss-eap/commonj/tests/commonj.windup.test.xml
rules-reviewed/jboss-eap/glassfish/tests/xml-glassfish.windup.test.xml
rules-reviewed/jboss-eap/jboss-eap4/tests/eap4-xml-config.windup.test.xml
rules-reviewed/jboss-eap/jboss-eap5/tests/jboss-eap5-java.windup.test.xml
rules-reviewed/jboss-eap/jboss-eap5/tests/jboss-eap5-xml.windup.test.xml
rules-reviewed/jboss-eap/jonas/tests/xml-jonas.windup.test.xml
rules-reviewed/jboss-eap/jrun/tests/xml-jrun.windup.test.xml
rules-reviewed/jboss-eap/orion/tests/xml-orion.windup.test.xml
rules-reviewed/jboss-eap/resin/tests/xml-resin.windup.test.xml
rules-reviewed/jboss-eap/uncategorized/tests/environment-dependent.windup.test.xml
rules-reviewed/jboss-eap/uncategorized/tests/ignore-references.windup.test.xml
rules-reviewed/jboss-eap/weblogic/tests/weblogic-ignore-references.windup.test.xml
rules-reviewed/jboss-eap/websphere/tests/websphere-mqe.windup.test.xml
rules-reviewed/jboss-eap/websphere/tests/websphere-other.windup.test.xml

some tests have got missing <rulepath> and added additional ns into <ruleset> or missing <rules> element.
And order for sourceMode was random so to reorder to be valid to XSD

WINDUP-710 follow-up to get all tests valid to xsd

---

rules-reviewed/droolsjbpm/kie-api.windup.xml
rules-reviewed/droolsjbpm/tests/data/Example.java
rules-reviewed/droolsjbpm/tests/kie-api.windup.test.xml

Rule set to classify droolsjbpm API changes to KIE. 
See [JIRA](https://issues.jboss.org/browse/WINDUPRULE-107)

WINDUPRULE-107 : Added ruleset for droolsjbpm api changes

---

pom.xml

https://issues.jboss.org/browse/WINDUP-911

WINDUP-911 take only *.windup.xml files for built jar artifact

---

rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml
rules-reviewed/eap6/jboss-eap5/jboss-eap5-java.windup.xml
rules-reviewed/eap6/jboss-eap5/jboss-eap5-xml.windup.xml

Comes with https://github.com/windup/windup/pull/840

WINDUP-918  MANDATORY -> mandatory

---

rules-reviewed/eap6/uncategorized/environment-dependent.windup.xml
rules-reviewed/eap6/uncategorized/tests/environment-dependent.windup.test.xml
rules-reviewed/eap6/weblogic/tests/weblogic-catchall.windup.test.xml
rules-reviewed/eap6/weblogic/tests/weblogic.windup.test.xml
rules-reviewed/eap6/weblogic/weblogic-catchall.windup.xml
rules-reviewed/eap6/weblogic/weblogic.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-120

Winduprule 120

---

rules-reviewed/eap7/eap6/eap6-xml.windup.xml
rules-reviewed/eap7/eap6/eap6.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-124

WINDUPRULE-124 added few fixes according to jira issue

---

rules-reviewed/eap6/jboss-eap5/jboss-eap5-xml.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-125

WINDUPRULE-125 fixed wrong paths to xsl files

---

rules-reviewed/eap7/eap6/hibernate4-xml.windup.xml
rules-reviewed/eap7/eap6/hibernate4.windup.xml
rules-reviewed/eap7/eap6/tests/data/data-hibernate4/HibernateUtil.java
rules-reviewed/eap7/eap6/tests/data/data-hibernate4/hibernate.cfg.xml
rules-reviewed/eap7/eap6/tests/data/data-hibernate4/hibernate.properties
rules-reviewed/eap7/eap6/tests/hibernate4-xml.windup.test.xml
rules-reviewed/eap7/eap6/tests/hibernate4.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-119

WINDUPRULE-119 hibernate 4 to 5 set of rules

---

rules-reviewed/eap7/eap6/eap6.windup.xml
rules-reviewed/eap7/eap6/tests/data/ClientKickOffExample.java
rules-reviewed/eap7/eap6/tests/eap6.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-129

WINDUPRULE-129 adding hornetq classification

---

rules-reviewed/eap7/eap6/eap6.windup.xml
rules-reviewed/eap7/eap6/tests/data/MyLogger.java
rules-reviewed/eap7/eap6/tests/data/UseFaceletContext.java
rules-reviewed/eap7/eap6/tests/eap6.windup.test.xml

I figured I will try to add some easier rules myself to better understand what it takes :-)

[WINDUPRULE-139] [WINDUPRULE-140] add rules for JBoss Logging annotations and JSF incompatibility

---

src/test/java/org/jboss/windup/rules/tests/WindupRulesTest.java

them all.
https://issues.jboss.org/browse/WINDUPRULE-133
This PR depends on https://github.com/windup/windup/pull/867 change!

WINDUPRULE-133 tests should be able to run all tests in file and capture

---

rules-reviewed/eap7/eap6/resteasy.windup.xml
rules-reviewed/eap7/eap6/tests/data/data-resteasy/JAXBElementProvider.java
rules-reviewed/eap7/eap6/tests/data/data-resteasy/MyHeaderInterceptor.java
rules-reviewed/eap7/eap6/tests/data/data-resteasy/MyInterceptor.java
rules-reviewed/eap7/eap6/tests/data/data-resteasy/PojoConverter.java
rules-reviewed/eap7/eap6/tests/data/data-resteasy/RestInvoker.java
rules-reviewed/eap7/eap6/tests/data/data-resteasy/RsCacheClient.java
rules-reviewed/eap7/eap6/tests/data/data-resteasy/RsClient.java
rules-reviewed/eap7/eap6/tests/data/data-resteasy/SeamResteasyResourceFactory.java
rules-reviewed/eap7/eap6/tests/resteasy.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-126

WINDUPRULE-126 new Resteasy rules for EAP7 migration

---

rules-reviewed/eap6/uncategorized/generic-catchall.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-149

WINDUPRULE-149 removed classification which duplicated hint/s

---

rules-reviewed/eap7/eap6/hsearch.windup.xml
rules-reviewed/eap7/eap6/tests/data/data-hsearch/Book.java
rules-reviewed/eap7/eap6/tests/data/data-hsearch/CacheServiceProvider.java
rules-reviewed/eap7/eap6/tests/data/data-hsearch/Hotel.java
rules-reviewed/eap7/eap6/tests/data/data-hsearch/HsearchUtil.java
rules-reviewed/eap7/eap6/tests/data/data-hsearch/JMSController.java
rules-reviewed/eap7/eap6/tests/data/data-hsearch/MyFTEventListener.java
rules-reviewed/eap7/eap6/tests/data/data-hsearch/MyStrategy.java
rules-reviewed/eap7/eap6/tests/data/data-hsearch/SecurityFilterFactory.java
rules-reviewed/eap7/eap6/tests/data/data-hsearch/pom.xml
rules-reviewed/eap7/eap6/tests/hsearch.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-130
There are still some issues - tests and probably rule definitions

WINDUPRULE-130 adding hibernate search rules for EAP7 migration

---

rules-reviewed/eap7/eap6/eap6-xml.windup.xml
rules-reviewed/eap7/eap6/eap6.windup.xml
rules-reviewed/eap7/eap6/hibernate4-xml.windup.xml
rules-reviewed/eap7/eap6/hibernate4.windup.xml
rules-reviewed/eap7/eap6/hsearch.windup.xml
rules-reviewed/eap7/eap6/resteasy.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-145

Winduprule-145

---

pom.xml
rules-reviewed/eap7/eap6/hibernate4.windup.xml
rules-reviewed/eap7/eap6/tests/data/data-hibernate4/HibernateUtil.java
rules-reviewed/eap7/eap6/tests/hibernate4.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-160
+
added java version based surefire argline due MaxPermSize option missing in Java 8

WINDUPRULE-160 fixed hibernate4-00002 rule

---

rules-reviewed/os/windows/os-specific.windup.xml
rules-reviewed/os/windows/tests/data/pom.xml
rules-reviewed/os/windows/tests/data/test.properties
rules-reviewed/os/windows/tests/os-specific.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-148

WINDUPRULE-148 adding Windows OS specific file system path

---

rules-reviewed/filemappings/default-package-to-organization-names.windup.xml
rules-reviewed/filemappings/file-mappings.windup.xml

https://issues.jboss.org/browse/WINDUP-1003
Relates to: https://github.com/windup/windup/pull/933

WINDUP-1003: Attach IDs to all filemapping and package-mapping rules

---

src/test/java/org/jboss/windup/rules/tests/WindupRulesTest.java

Related: https://github.com/windup/windup/pull/926
Follows up on: https://github.com/windup/windup/pull/924

Tweaked to match projectmodel changes

---

rules-reviewed/eap7/eap6/hsearch.windup.xml
rules-reviewed/eap7/eap6/tests/data/data-hsearch/HsearchUtil.java
rules-reviewed/eap7/eap6/tests/hsearch.windup.test.xml

this depends on https://github.com/windup/windup/pull/927
https://issues.jboss.org/browse/WINDUPRULE-151

WINDUPRULE-151

---

rules-reviewed/eap6/weblogic/weblogic-services.windup.xml

some cleaning and new comment ;)
I haven't catched the merge from @jsight

WINDUPRULE-175 adding comment for later and cleaning the OR elements

---

rules-reviewed/eap6/java-ee/seam/seam-ui.windup.xml
rules-reviewed/eap7/eap5/jboss-eap5-7-xml.windup.xml
rules-reviewed/eap7/eap6/eap6-xml.windup.xml
rules-reviewed/eap7/eap6/eap6.windup.xml
rules-reviewed/eap7/eap6/hibernate4-xml.windup.xml

This is "backport" of changes for 2.7.0 work

taiga task #213 updated links to docs for eap5/7 related rulesets

---

rules-reviewed/eap6/glassfish/xml-glassfish.windup.xml
rules-reviewed/eap6/jboss-eap5/jboss-eap5-xml.windup.xml
rules-reviewed/eap6/jonas/xml-jonas.windup.xml
rules-reviewed/eap6/jrun/xml-jrun.windup.xml
rules-reviewed/eap6/orion/xml-orion.windup.xml
rules-reviewed/eap6/resin/xml-resin.windup.xml
rules-reviewed/eap6/weblogic/weblogic-webservices.windup.xml
rules-reviewed/hibernate/hibernate-xml.windup.xml
rules-reviewed/hibernate/hibernate.windup.xml

@bergerhoffer : Would you mind doing a review of these updated links to our docs?

JBEAP-2704: Update JBoss EAP 6 documentation links to point to the latest 6.4 version

---

rules-reviewed/eap7/eap6/hibernate4-xml.windup.xml
rules-reviewed/eap7/eap6/hibernate4.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-161
@sgilda got head up with updated/enhanced migration guide for Hibernate 5

WINDUPRULE-161 changed hibernate 5 doc links

---

rules-reviewed/droolsjbpm/kie-api.windup.xml
rules-reviewed/eap6/java-ee/seam/seam-ui.windup.xml
rules-reviewed/eap6/weblogic/weblogic.windup.xml
rules-reviewed/eap7/eap5/jboss-eap5-7-java.windup.xml
rules-reviewed/eap7/eap6/eap6-xml.windup.xml
rules-reviewed/eap7/eap6/hibernate4-xml.windup.xml
rules-reviewed/eap7/eap6/hibernate4.windup.xml

https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/249

first draft of quickfixes in some rules triggered in our jee-example-app

---

rules-reviewed/eap6/java-ee/java-ee-jaxrpc.windup.xml
rules-reviewed/eap6/uncategorized/environment-dependent.windup.xml
rules-reviewed/eap6/weblogic/tests/data/java-wsdl-mapping.xml
rules-reviewed/eap6/weblogic/tests/weblogic-xml-descriptors.windup.test.xml
rules-reviewed/eap6/weblogic/weblogic-services.windup.xml
rules-reviewed/eap6/weblogic/weblogic-webapp.windup.xml
rules-reviewed/eap6/weblogic/weblogic-xml-descriptors.windup.xml
rules-reviewed/eap6/weblogic/weblogic.windup.xml
rules-reviewed/eap6/websphere/tests/data/WebsphereCatchAllSample.java
rules-reviewed/eap6/websphere/tests/websphere-catchall.windup.test.xml
rules-reviewed/eap6/websphere/tests/websphere-xml.windup.test.xml
rules-reviewed/eap6/websphere/websphere-catchall.windup.xml
rules-reviewed/eap6/websphere/websphere-xml.windup.xml

This PR is enhanced PR from https://github.com/windup/windup-rulesets/pull/172
Not wanted changes are missing and there are accompanying tests changes too.

Maarc changes polished

---

rules-reviewed/droolsjbpm/kie-api.windup.xml
rules-reviewed/eap6/jboss-eap5/jboss-eap5-java.windup.xml
rules-reviewed/eap6/weblogic/weblogic-webapp.windup.xml
rules-reviewed/eap6/weblogic/weblogic.windup.xml
rules-reviewed/eap7/eap5/jboss-eap5-7-java.windup.xml
rules-reviewed/eap7/eap6/eap6.windup.xml
rules-reviewed/eap7/eap6/hsearch.windup.xml
rules-reviewed/hibernate/hibernate-xml.windup.xml
rules-reviewed/hibernate/tests/hibernate-xml.windup.test.xml

Some additional quickfixes for replacing imports and annotations

adding quickfixes to some additional rules

---

src/test/java/org/jboss/windup/rules/tests/WindupRulesTest.java

Related: https://github.com/windup/windup/pull/1036

WINDUP-1221: Fixed to be compatible with the new API

---

rules-reviewed/eap7/eap6/hsearch.windup.xml
rules-reviewed/os/windows/os-specific.windup.xml

This dramatically sped up the large app test for me.

Removed a superfluous 'or' and added restrictions to a parameter

---

rules-reviewed/droolsjbpm/kie-api.windup.xml

Changed id to appropriate value.

Fixed id in kie-api windup rules

---

rules-reviewed/eap6/java-ee/seam/seam-ui.windup.xml
rules-reviewed/openshift/local-storage.windup.xml
rules-reviewed/openshift/tests/local-storage.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-196

WINDUPRULE-196 - fixed too greedy regex pattern for local file paths

---

rules-reviewed/eap6/uncategorized/environment-dependent.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-179

WINDUPRULE-179 adding environment-dependent ruleset for EAP7

---

rules-reviewed/eap6/websphere/websphere-xml.windup.xml
rules-reviewed/eap7/websphere/tests/data/deployment.xml
rules-reviewed/eap7/websphere/websphere-xml.windup.xml

Other part: https://github.com/windup/windup/pull/1105
(Doesn't really depend)

T752 WebSphere descriptors mandatory

---

rules-reviewed/eap6/uncategorized/environment-dependent.windup.xml
rules-reviewed/eap6/weblogic/tests/weblogic-catchall.windup.test.xml
rules-reviewed/eap6/weblogic/weblogic-catchall.windup.xml
rules-reviewed/eap7/eap5/jboss-eap5-7-java.windup.xml
rules-reviewed/eap7/eap5/jboss-eap5-7-xml.windup.xml
rules-reviewed/eap7/eap5/tests/jboss-eap5-7-java.windup.test.xml
rules-reviewed/eap7/eap5/tests/jboss-eap5-7-xml.windup.test.xml
rules-reviewed/eap7/eap6/eap6-xml.windup.xml
rules-reviewed/eap7/weblogic/weblogic-xml-descriptors.windup.xml
rules-reviewed/eap7/websphere/tests/websphere-xml.windup.test.xml
rules-reviewed/eap7/websphere/websphere-xml.windup.xml
rules-reviewed/openshift/jni-native-code.windup.xml

tasks from US https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/us/983 related to duplicated classifications in java vs xml rules or movings to mandatory category

Taiga tasks rulesets

---

rules-reviewed/os/windows/os-specific.windup.xml
rules-reviewed/os/windows/tests/data/JSEncoder.java
rules-reviewed/os/windows/tests/data/test.properties
rules-reviewed/os/windows/tests/os-specific.windup.test.xml

excluded js files, 
changed tag to ms-windows,
changed category-id to cloud-mandatory from mandatory
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/1019

task1019 - fixed regex to exclude some occurences,

---

rules-reviewed/os/windows/os-specific.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-224

WINDUPRULE-224 - rolled back the category change from previous PR #208

---

rules-reviewed/eap6/java-ee/seam/seam-ui.windup.xml
rules-reviewed/eap6/weblogic/tests/weblogic-catchall.windup.test.xml
rules-reviewed/eap6/weblogic/weblogic-catchall.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-221
- first removed "found" word from WebLogic catchall ruleset
- second added into all BEA WebLogic related rules "BEA"

Winduprule 221

---

rules-reviewed/openshift/java-rmi.windup.xml
rules-reviewed/openshift/tests/java-rmi.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-222
https://issues.jboss.org/browse/WINDUPRULE-223

Winduprule-223 and 222

---

rules-reviewed/eap6/websphere/websphere-xml.windup.xml
rules-reviewed/eap7/websphere/websphere-xml.windup.xml

Descriptions and links have been enhanced both for rules with target EAP 6 and EAP 7.

WINDUPRULE-217 Enhance WebSphere WS (Extension|Client|Binding) 

---

rules-reviewed/eap7/eap6/hibernate4-xml.windup.xml
rules-reviewed/eap7/eap6/hibernate4.windup.xml
rules-reviewed/eap7/eap6/hsearch.windup.xml
rules-reviewed/eap7/eap6/resteasy.windup.xml
rules-reviewed/eap7/websphere/tests/websphere-mq.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-227

WINDUPRULE-227

---

rules-reviewed/eap7/eap5/jboss-eap5-7-xml.windup.xml

Resolves JIRA https://issues.jboss.org/browse/WINDUPRULE-236

Update jboss-eap5-7-xml-13000 effort

---

rules-reviewed/eap7/eap5and6/jboss-eap5and6to7-java.windup.xml

Update jboss-eap5and6to7-java-09000 title

---

rules-reviewed/eap6/uncategorized/environment-dependent.windup.xml
rules-reviewed/eap6/uncategorized/tests/environment-dependent.windup.test.xml

#close WINDUPRULE-240 WINDUPRULE-239 WINDUPRULE-238

Split rule environment-dependent-calls-04000 into 2 rules

---

rules-reviewed/eap6/jboss-eap5/jboss-eap5-java.windup.xml
rules-reviewed/eap7/eap5/jboss-eap5-7-java.windup.xml

- changes hint's title according to requirement
- found better link (Oracle official JMS docs) rather than using the suggested link
- updated the link in hint to EAP 7 doc because it was broken

WINDUPRULE-243 Rules jboss-eap5-java-02000 and jboss-eap5-7-java-02000 improvements

---

rules-reviewed/eap6/jboss-eap5/jboss-eap5-xml.windup.xml
rules-reviewed/eap6/websphere/websphere-xml.windup.xml
rules-reviewed/eap7/eap6/eap6-xml.windup.xml
rules-reviewed/eap7/websphere/websphere-xml.windup.xml

Related to https://github.com/windup/windup/pull/1139

WINDUPRULE-257 Fix 'Windup-generated' in 'RHAMT-generated'

---

rules-reviewed/eap7/eap5/jboss-eap5-7-java.windup.xml
rules-reviewed/eap7/eap5/tests/jboss-eap5-7-java.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-258

WINDUPRULE-258: changed hint title and recommendation for @Service

---

rules-reviewed/eap6/java-ee/seam/seam-ui.windup.xml
rules-reviewed/eap6/java-ee/seam/tests/seam-ui.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-256

WINDUPRULE-256: fixed formatting of xml elements in Seam UI rules

---

rules-reviewed/eap7/eap5/jboss-eap5-7-xml.windup.xml
rules-reviewed/eap7/eap5and6/jboss-eap5and6to7-xml.windup.xml
rules-reviewed/eap7/weblogic/weblogic-xml-descriptors.windup.xml
rules-reviewed/eap7/websphere/websphere-mq.windup.xml

- fixed 1 broken link ([this one](https://github.com/windup/windup-rulesets/compare/master...mrizzi:JIRA_WINDUP-1485?expand=1#diff-71269e28097c66bdc44626717769f11cL62))
- moved the `/paged` URL to the `/html-single` one

WINDUP-1485 Fix broken link to EAP documentation

---

rules-reviewed/eap6/jboss-eap5/jboss-eap5-xml.windup.xml
rules-reviewed/eap6/weblogic/tests/weblogic-xml-descriptors.windup.test.xml
rules-reviewed/eap6/weblogic/weblogic-webapp.windup.xml
rules-reviewed/eap6/weblogic/weblogic-webservices.windup.xml
rules-reviewed/eap6/weblogic/weblogic-xml-descriptors.windup.xml
rules-reviewed/eap6/weblogic/weblogic.windup.xml
rules-reviewed/eap6/websphere/tests/websphere-xml.windup.test.xml
rules-reviewed/eap6/websphere/websphere-xml.windup.xml
rules-reviewed/eap7/weblogic/weblogic-xml-descriptors.windup.xml
rules-reviewed/eap7/websphere/websphere-jms.windup.xml
rules-reviewed/eap7/websphere/websphere-xml.windup.xml

This is an extract from https://github.com/windup/windup-rulesets/pull/250

Back-port of changes from EAP 7 to 6 and various fixes

---

rules-reviewed/eap6/jboss-eap5/jboss-eap5-xml.windup.xml
rules-reviewed/eap6/jboss-eap5/tests/jboss-eap5-xml.windup.test.xml

subtask https://issues.jboss.org/browse/WINDUPRULE-271 for https://issues.jboss.org/browse/WINDUPRULE-265

WINDUPRULE-271: updating hint title and recommendation

---

rules-reviewed/eap6/weblogic/weblogic-xml-descriptors.windup.xml
rules-reviewed/eap6/weblogic/weblogic.windup.xml
rules-reviewed/eap7/weblogic/tests/weblogic-webservices.windup.test.xml
rules-reviewed/eap7/weblogic/weblogic-webservices.windup.xml
rules-reviewed/eap7/weblogic/weblogic-xml-descriptors.windup.xml
rules-reviewed/eap7/websphere/websphere-xml.windup.xml

The comparison result after https://github.com/windup/windup-rulesets/pull/251 and some other changes, which are now in PR queue
ref. https://issues.jboss.org/browse/WINDUPRULE-264

WINDUPRULE-264: syncing EAP6/7 similar rules

---

rules-reviewed/openshift/logging.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-280

WINDUPRULE-280: fixed typo in logging-0000

---

rules-reviewed/core.windup.categories.xml

https://issues.jboss.org/browse/WINDUPRULE-281

WINDUPRULE-281: Updated category names

---

rules-reviewed/technology-usage/markup-technology-usage.windup.xml
rules-reviewed/technology-usage/tests/data/markup/example.css
rules-reviewed/technology-usage/tests/data/markup/index.html
rules-reviewed/technology-usage/tests/data/markup/myScript.js
rules-reviewed/technology-usage/tests/markup-technology-usage.windup.test.xml

Depends on https://github.com/windup/windup/pull/1175

WINDUPRULE-286 Statistics Rules: View:Markup (HTML, CSS, JS)

---

rules-reviewed/technology-usage/tests/data/web/AppletTest.java
rules-reviewed/technology-usage/tests/data/web/JAppletTest.java
rules-reviewed/technology-usage/tests/data/web/WebSockets.java
rules-reviewed/technology-usage/tests/data/web/jsf/main.xhtml
rules-reviewed/technology-usage/tests/data/web/jsf/test.jsp
rules-reviewed/technology-usage/tests/data/web/sample.jnlp
rules-reviewed/technology-usage/tests/data/web/web.xml
rules-reviewed/technology-usage/tests/web-technology-usage.windup.test.xml
rules-reviewed/technology-usage/web-technology-usage.windup.xml

Just to demonstrate a few different approaches, as these are a little different. Tests are not yet complete.

Winduprule 284: Web technologies (JSF, JSP, etc)

---

rules-reviewed/technology-usage/jta-technology-usage.windup.xml
rules-reviewed/technology-usage/tests/data/jta/hibernate.cfg.xml
rules-reviewed/technology-usage/tests/data/jta/persistence.xml
rules-reviewed/technology-usage/tests/jta-technology-usage.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-295
depends on https://github.com/windup/windup/pull/1179

WINDUPRULE-295: adding JTA technology stats rules

---

rules-reviewed/technology-usage/javaee-technology-usage.windup.xml
rules-reviewed/technology-usage/tests/data/javaee/JsonController.java
rules-reviewed/technology-usage/tests/data/javaee/META-INF/batch-jobs/batch-job1.xml
rules-reviewed/technology-usage/tests/data/javaee/UserBean.java
rules-reviewed/technology-usage/tests/data/javaee/batch.xml
rules-reviewed/technology-usage/tests/javaee-technology-usage.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-296

WINDUPRULE-296: adding javaee rules for Technology stats

---

rules-reviewed/technology-usage/connect-technology-usage.windup.xml
rules-reviewed/technology-usage/tests/connect-technology-usage.windup.test.xml
rules-reviewed/technology-usage/tests/data/connect/Hello.java
rules-reviewed/technology-usage/tests/data/connect/HelloImpl.java
rules-reviewed/technology-usage/tests/data/connect/JNI.java
rules-reviewed/technology-usage/tests/data/connect/Mail.java
rules-reviewed/technology-usage/tests/data/connect/XAExceptionSessionBean.java
rules-reviewed/technology-usage/tests/data/connect/ra.xml

WINDUPRULE-290 - connect technologies identification

---

rules-reviewed/eap7/eap6/eap6.windup.xml
rules-reviewed/eap7/eap6/tests/data/UseFaceletContext.java
rules-reviewed/eap7/eap6/tests/eap6.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-303

WINDUPRULE-303: adding https URL CN check change in system property

---

rules-reviewed/technology-usage/javaee-technology-usage.windup.xml
rules-reviewed/technology-usage/tests/javaee-technology-usage.windup.test.xml

fixing WINDUPRULE-296 after @OndraZizka catch it doesn't have what the doc specified.

WINDUPRULE-296: fixed java ee technology tags

---

rules-reviewed/eap6/uncategorized/environment-dependent.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-310

WINDUPRULE-310: adding EAP7 documentation link

---

rules-reviewed/technology-usage/database-technology-usage.windup.xml
rules-reviewed/technology-usage/tests/data/database/AnnotationMultipleDs.java
rules-reviewed/technology-usage/tests/data/database/AnnotationSingleDs.java
rules-reviewed/technology-usage/tests/data/database/Room.java
rules-reviewed/technology-usage/tests/data/database/mysql-ds.xml
rules-reviewed/technology-usage/tests/data/database/persistence.xml
rules-reviewed/technology-usage/tests/database-technology-usage.windup.test.xml

Depends on: https://github.com/windup/windup/pull/1201

WINDUPRULE-292 - database

---

rules-reviewed/eap6/websphere/tests/websphere-jms.windup.test.xml
rules-reviewed/eap6/websphere/websphere-jms.windup.xml
rules-reviewed/eap7/websphere/tests/websphere-jms.windup.test.xml
rules-reviewed/eap7/websphere/websphere-jms.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-319

WINDUPRULE-319

---

rules-reviewed/openshift/java-rmi.windup.xml
rules-reviewed/openshift/jni-native-code.windup.xml
rules-reviewed/openshift/tests/java-rmi.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-320

WINDUPRULE-320: Switched to non-parameterized approach as it was not needed and vastly lowered performance in some cases

---

rules-reviewed/eap7/eap5/jboss-eap5-7-xml.windup.xml

Fixed link to point to EAP 7 docs

WINDUPRULE-323 jboss-eap5-7-xml-13000 referencing EAP 7 docs

---

rules-reviewed/eap6/uncategorized/environment-dependent.windup.xml

WINDUPRULE-324 Rewording of a Rule to reference EAP

---

rules-reviewed/eap6/uncategorized/environment-dependent.windup.xml
rules-reviewed/eap6/uncategorized/tests/environment-dependent.windup.test.xml

WINDUPRULE-324 Rewording of a Rule to reference EAP (test fix)

---

rules-reviewed/hibernate/hibernate-catchall.windup.xml

Porting of #298 to 4.0.x branch

WINDUPRULE-332 Remove 'reviewed-2015-09-23' tag

---

rules-reviewed/eap7/weblogic/weblogic-jms.windup.xml
rules-reviewed/eap7/websphere/websphere-mqe.windup.xml

Porting of #300 to 4.0.x branch

WINDUPRULE-333 - EAP 7 rules: update target from '[6,8)' to '[7,8)'

---

pom.xml
src/test/java/org/jboss/windup/rules/tests/WindupRulesTest.java

Related PR: https://github.com/windup/windup/pull/1264

Ported to tinkerpop 3

---

rules-reviewed/eap6/weblogic/weblogic-webservices.windup.xml
rules-reviewed/eap7/weblogic/weblogic-webservices.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-336

WINDUPRULE-336: Rule "weblogic-webservices-eap7-05000" Title Change

---

rules-reviewed/eap6/jboss-eap5/jboss-eap5-xml.windup.xml
rules-reviewed/eap7/eap5/jboss-eap5-7-xml.windup.xml
rules-reviewed/eap7/eap5/tests/jboss-eap5-7-xml.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-334

WINDUPRULE-334: Merge classloader rules

---

rules-reviewed/eap6/weblogic/weblogic-webservices.windup.xml
rules-reviewed/eap7/weblogic/weblogic-webservices.windup.xml

4.0.x backport: https://github.com/windup/windup-rulesets/pull/305

(4.0.x) WINDUPRULE-336: Rule "weblogic-webservices-eap7-05000" Title Change

---

rules-reviewed/eap6/jboss-eap5/jboss-eap5-java.windup.xml
rules-reviewed/eap6/jboss-eap5/tests/samples/java/SampleService.java
rules-reviewed/eap7/eap4and5/jboss-eap4and5to6and7-java.windup.xml
rules-reviewed/eap7/eap4and5/jboss-eap4and5to6and7-xml.windup.xml
rules-reviewed/eap7/eap4and5/tests/data/java/JNDIMap.java
rules-reviewed/eap7/eap4and5/tests/data/java/JNDIMapMBean.java
rules-reviewed/eap7/eap4and5/tests/data/java/TestClass.java
rules-reviewed/eap7/eap4and5/tests/data/xml/jboss-service.xml
rules-reviewed/eap7/eap4and5/tests/data/xml/jboss-web.xml
rules-reviewed/eap7/eap4and5/tests/data/xml/jboss.xml
rules-reviewed/eap7/eap4and5/tests/data/xml/login-config.xml
rules-reviewed/eap7/eap4and5/tests/jboss-eap4and5to6and7-java.windup.test.xml
rules-reviewed/eap7/eap4and5/tests/jboss-eap4and5to6and7-xml.windup.test.xml

This PR contains all the implementations for the sub-issues of the [WINDUPRULE-103](https://issues.jboss.org/browse/WINDUPRULE-103).
For every issue i reported what i've changed from the request in JIRA.
[WINDUPRULE-182](https://issues.jboss.org/browse/WINDUPRULE-182)
Used link to redhat.com, NOT docs.jboss.org
[WINDUPRULE-183](https://issues.jboss.org/browse/WINDUPRULE-183)
Added link to JBoss EAP 6.4 Migration guide
[WINDUPRULE-185](https://issues.jboss.org/browse/WINDUPRULE-185)
Added link to JBoss EAP 6.4 Migration guide
[WINDUPRULE-187](https://issues.jboss.org/browse/WINDUPRULE-187)
Added link to JBoss EAP 6.4 Migration guide
[WINDUPRULE-188](https://issues.jboss.org/browse/WINDUPRULE-188)
link to javadoc for class JMX to complete the case …

WINDUPRULE-103 Missing EAP 4+5 rules

---

rules-reviewed/eap6/commonj/commonj.windup.xml
rules-reviewed/eap6/glassfish/xml-glassfish.windup.xml
rules-reviewed/eap6/java-ee/java-ee-jaxrpc.windup.xml
rules-reviewed/eap6/java-ee/xml-webservices.windup.xml
rules-reviewed/eap6/jboss-eap4/eap4-xml-config.windup.xml
rules-reviewed/eap6/jonas/xml-jonas.windup.xml
rules-reviewed/eap6/jrun/jrun-catchall.windup.xml
rules-reviewed/eap6/jrun/xml-jrun.windup.xml
rules-reviewed/eap6/jsp/jsp.windup.xml
rules-reviewed/eap6/log4j/log4j.windup.xml
rules-reviewed/eap6/orion/xml-orion.windup.xml
rules-reviewed/eap6/resin/xml-resin.windup.xml
rules-reviewed/eap6/uncategorized/generic-catchall.windup.xml
rules-reviewed/eap6/uncategorized/ignore-references.windup.xml

- Setting the target to EAP 6+ for some rules 
- Fixing some 404 for some EAP 6 doc’s links

WINDUPRULE-326 Target EAP 6+ for some EAP 6 rules

---

rules-reviewed/eap6/jboss-eap5/jboss-eap5-java.windup.xml
rules-reviewed/eap6/jboss-eap5/tests/samples/java/SampleService.java
rules-reviewed/eap7/eap4and5/jboss-eap4and5to6and7-java.windup.xml
rules-reviewed/eap7/eap4and5/jboss-eap4and5to6and7-xml.windup.xml
rules-reviewed/eap7/eap4and5/tests/data/java/JNDIMap.java
rules-reviewed/eap7/eap4and5/tests/data/java/JNDIMapMBean.java
rules-reviewed/eap7/eap4and5/tests/data/java/TestClass.java
rules-reviewed/eap7/eap4and5/tests/data/xml/jboss-service.xml
rules-reviewed/eap7/eap4and5/tests/data/xml/jboss-web.xml
rules-reviewed/eap7/eap4and5/tests/data/xml/jboss.xml
rules-reviewed/eap7/eap4and5/tests/data/xml/login-config.xml
rules-reviewed/eap7/eap4and5/tests/jboss-eap4and5to6and7-java.windup.test.xml
rules-reviewed/eap7/eap4and5/tests/jboss-eap4and5to6and7-xml.windup.test.xml

WINDUPRULE-103 Missing EAP 4+5 rules (#302)

---

rules-reviewed/os/windows/os-specific.windup.xml

WINDUPRULE-338 os-specific-00001 remove source=windows (#310)

---

rules-reviewed/eap7/eap5/jboss-eap5-7-xml.windup.xml

porting of #312 to master branch

WINDUPRULE-335 Jboss security configuration descriptor

---

rules-reviewed/eap7/eap4and5/jboss-eap4and5to6and7-xml.windup.xml
rules-reviewed/eap7/eap4and5/tests/data/xml/jboss-beans.xml
rules-reviewed/eap7/eap4and5/tests/jboss-eap4and5to6and7-xml.windup.test.xml

WINDUPRULE-339 jboss-beans.xml not detected (#314)

---

src/test/java/org/jboss/windup/rules/tests/WindupRulesTest.java

Change needed after https://github.com/windup/windup/pull/1280 will be merged

Ci intermittent failures

---

rules-reviewed/eap6/weblogic/tests/data-webservicetests/TransactionPojoImpl.java
rules-reviewed/eap6/weblogic/tests/weblogic-webservices.windup.test.xml
rules-reviewed/eap6/weblogic/weblogic-webapp.windup.xml
rules-reviewed/eap6/weblogic/weblogic-webservices.windup.xml
rules-reviewed/eap7/weblogic/tests/data-webservicetests/TransactionPojoImpl.java
rules-reviewed/eap7/weblogic/tests/weblogic-webservices.windup.test.xml
rules-reviewed/eap7/weblogic/weblogic-webservices.windup.xml

- created new rules as requested for EAP both 6 & 7
- fixed a link in `weblogic-webapp-08000` to JBoss EAP 6 javadoc that was wrong (404 page)

WINDUPRULE-205 new rule for weblogic.jws.Transactional annotation

---

rules-reviewed/eap7/eap5/base64.windup.xml
rules-reviewed/eap7/eap5/tests/base64.windup.test.xml
rules-reviewed/eap7/eap5/tests/data/java/Base64Sample.java

https://issues.jboss.org/browse/WINDUPRULE-40

WINDUPRULE-40: Added rule for org.jboss.util.Base64

---

rules-reviewed/eap6/jboss-eap5/jboss-eap5-java.windup.xml
rules-reviewed/eap6/jboss-eap5/tests/jboss-eap5-java.windup.test.xml
rules-reviewed/eap6/jboss-eap5/tests/samples/java/JBossWSSampleData.java
rules-reviewed/eap7/eap5/jboss-eap5-7-java.windup.xml
rules-reviewed/eap7/eap5/tests/data/java/JBossWSSampleData.java
rules-reviewed/eap7/eap5/tests/jboss-eap5-7-java.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-19

WINDUPRULE-19: JBoss WS Package Relocations

---

pom.xml
rules-reviewed/eap6/glassfish/java-glassfish.windup.groovy
rules-reviewed/eap6/glassfish/tests/data/MessageDrivenNoSubclass.java
rules-reviewed/eap6/glassfish/tests/data/MessageDrivenSubclass.java
rules-reviewed/eap6/glassfish/tests/java-glassfish.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-331
Depends on: https://github.com/windup/windup/pull/1298

WINDUPRULE-331: JBoss EAP requires a MessageDriven bean to implement a MessageListener interface

---

.gitignore
pom.xml
src/test/java/org/jboss/windup/rules/tests/ParameterizedArquillianRunner.java
src/test/java/org/jboss/windup/rules/tests/RuleTest.java
src/test/java/org/jboss/windup/rules/tests/RuleTestHandler.java
src/test/java/org/jboss/windup/rules/tests/RulesPath.java
src/test/java/org/jboss/windup/rules/tests/TestRulesPath.java
src/test/java/org/jboss/windup/rules/tests/WindupFrameworkMethod.java
src/test/java/org/jboss/windup/rules/tests/WindupRulesMultipleTests.java

WIP for review/ideas, particularly on usage of RuleExecutionResultsListener.
This PR is dependent on core [PR-1327](https://github.com/windup/windup/pull/1327)

Windup 2000

---

rules-reviewed/openshift/session.windup.xml
rules-reviewed/openshift/tests/session.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-360

WINDUPRULE-360: add new developer network blog post to hint

---

pom.xml
rules-reviewed/technology-usage/embedded-framework.windup.xml

Depends on https://github.com/windup/windup/pull/1332

WINDUP-2171 JDK 11 compatibility - CLI

---

rules-reviewed/eap7/eap71/hibernate51-53.windup.xml
rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate515301200.java
rules-reviewed/eap7/eap71/tests/hibernate51-53.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-388

WINDUPRULE-388 Hibernate getType method renamed

---

rules-reviewed/eap7/eap71/hibernate51-53.windup.xml
rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate51530040X.java
rules-reviewed/eap7/eap71/tests/hibernate51-53.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-380

WINDUPRULE-380 SessionFactoryImplementor methods removed

---

rules-reviewed/eap7/eap71/hibernate51-53.windup.xml
rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate515300600.java
rules-reviewed/eap7/eap71/tests/hibernate51-53.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-382

WINDUPRULE-382 QueryCacheFactory implementations

---

rules-reviewed/eap7/eap71/hibernate51-53.windup.groovy
rules-reviewed/eap7/eap71/hibernate51-53.windup.xml
rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate515300000_0.java
rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate515300000_1.java
rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate515300000_2.java
rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate515300001_0.java
rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate515300001_1.java
rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/SessionImplementor.java
rules-reviewed/eap7/eap71/tests/hibernate51-53.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-376

WINDUPRULE-376 SessionImplementor parameter changed to SharedSessionContractImplementor

---

rules-reviewed/eap7/eap71/hibernate51-53.windup.xml
rules-reviewed/eap7/eap71/tests/data/data-hibernate51-53/Hibernate515300800.java
rules-reviewed/eap7/eap71/tests/hibernate51-53.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-384

WINDUPRULE-384 Persister and Tuplizer changes

---

rules-reviewed/technology-usage/javaee-technology-tag.windup.groovy
rules-reviewed/technology-usage/tests/javaee-technology-tag.windup.test.xml

https://issues.jboss.org/browse/WINDUP-2360

Windup 2360 add technology tags

---

pom.xml
rules-reviewed/core.windup.label.xml

https://issues.jboss.org/browse/WINDUP-2332
This PR adds the default label file configuration to detect Target Runtimes

Windup 2332 - Application List Filtering/Labelling to support Target Runtime Selection

---

rules-reviewed/core.windup.label.xml

https://issues.jboss.org/browse/WINDUP-2492
Remove the character ">" from MEJB tag

WINDUP-2492: Application List Report - Technology Tags

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml
rules-reviewed/camel3/camel2/tests/data/java-generic-information/MyAggregationStrategy.java
rules-reviewed/camel3/camel2/tests/java-generic-information.windup.test.xml

https://issues.jboss.org/browse/WINDUPRULE-407
To run the validation test execute:
`$ mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=java-generic-information clean surefire-report:report`

WINDUPRULE-407 AggregationStrategy has been moved

---

rules-reviewed/camel3/camel2/tests/data/xml-renamed-components/pom.xml
rules-reviewed/camel3/camel2/tests/xml-renamed-components.windup.test.xml
rules-reviewed/camel3/camel2/xml-renamed-components.windup.xml

https://issues.jboss.org/browse/WINDUPRULE-410
Tested executing $ mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=xml-renamed-components clean surefire-report:report

WINDUPRULE-410 camel-rxjava2 renamed

---

rules-reviewed/eap7/eap72/maven-jboss-rmi-api_1.0_spec.rhamt.xml
rules-reviewed/eap7/eap72/tests/data/data-maven-jboss-rmi-api_1.0_spec/pom.xml
rules-reviewed/eap7/eap72/tests/maven-jboss-rmi-api_1.0_spec.rhamt.test.xml

Issue: https://issues.jboss.org/browse/WINDUPRULE-401
Please do not merge, link tag to be fixed once EAP 7.3 is released

WINDUPRULE-401: eap 7.3 maven-jboss-rmi-api_1.0_spec rule

---

rules-reviewed/eap6/websphere/websphere-xml.windup.xml
rules-reviewed/eap7/websphere/websphere-xml.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-439

WINDUPRULE-439 Fixed broken links using latest IBM docs

---

rules-reviewed/eap7/eap72/deprecated-singletonpolicy.rhamt.xml
rules-reviewed/eap7/eap72/tests/data/data-deprecated-singletonpolicy/ServiceActivator.java
rules-reviewed/eap7/eap72/tests/deprecated-singletonpolicy.rhamt.test.xml

Issue: https://issues.jboss.org/browse/WINDUPRULE-405

WINDUPRULE-405: eap 7.3 deprecated ha singleton api rules

---

rules-reviewed/camel3/camel2/tests/data/xml-renamed-components/pom.xml
rules-reviewed/camel3/camel2/tests/xml-renamed-components.windup.test.xml
rules-reviewed/camel3/camel2/xml-renamed-components.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-411
Thanks !

WINDUPRULE-411 Camel 3 springboot starters groupId have been renamed

---

pom.xml

https://issues.redhat.com/browse/WINDUPRULE-441

WINDUPRULE-441 Increase max memory when testing

---

rules-reviewed/eap7/eap72/maven-javax-to-jakarta.rhamt.xml
rules-reviewed/eap7/eap72/tests/data/data-maven-javax-to-jakarta/pom.xml
rules-reviewed/eap7/eap72/tests/maven-javax-to-jakarta.rhamt.test.xml

Issue: https://issues.jboss.org/browse/WINDUPRULE-396

WINDUPRULE-396: eap 7.3 maven-javax-to-jakarta rules

---

rules-reviewed/eap7/eap72/move-to-microprofile-rest-client-1.3.rhamt.xml
rules-reviewed/eap7/eap72/tests/data/data-move-to-microprofile-rest-client-1.3/RestClientProxyTest.java
rules-reviewed/eap7/eap72/tests/move-to-microprofile-rest-client-1.3.rhamt.test.xml

Issue: https://issues.redhat.com/browse/WINDUPRULE-400

WINDUPRULE-400: eap 7.3 move to mp rest client 1.3

---

rules-reviewed/camel3/camel2/tests/data/xml-removed-components/pom.xml
rules-reviewed/camel3/camel2/tests/xml-removed-components.windup.test.xml
rules-reviewed/camel3/camel2/xml-removed-components.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-423

WINDUPRULE-423 camel-script has been removed

---

rules-reviewed/rhr/springboot/springboot-associated-artifacts.rhamt.xml
rules-reviewed/rhr/springboot/tests/data/springboot-associated/pom.xml
rules-reviewed/rhr/springboot/tests/springboot-associated-artifacts.rhamt.test.xml

https://issues.redhat.com/browse/WINDUPRULE-406

WINDUPRULE-406: non-productized spring boot rules

---

rules-reviewed/eap7/eap72/move-to-microprofile-rest-client-1.3.rhamt.xml

Issue: https://issues.redhat.com/browse/WINDUPRULE-459

[WINDUPRULE-459] update move-to-microprofile-rest-client-1.3 rule link

---

rules-reviewed/camel3/camel2/tests/data/xml-moved-components/RouteBuilder.java
rules-reviewed/camel3/camel2/tests/data/xml-moved-components/blueprint.xml
rules-reviewed/camel3/camel2/tests/data/xml-moved-components/context.xml
rules-reviewed/camel3/camel2/tests/data/xml-moved-components/pom.xml
rules-reviewed/camel3/camel2/tests/xml-moved-components.windup.test.xml
rules-reviewed/camel3/camel2/xml-moved-components.windup.xml

JIRA issue:  https://issues.redhat.com/browse/WINDUPRULE-431

[WINDUPRULE-431 add rule for the components that was separated out of camel-core

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-466

WINDUPRULE-466: camel rule quickfix inoperative

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-467

WINDUPRULE-467: remove parameterized quickfix in rules

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml
rules-reviewed/camel3/camel2/tests/data/java-generic-information/Application.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/CustomRoutePolicyTest.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/EmptyProducerCache.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/Jt400Component.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/LogProducer.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/MailIdempotentRepositoryDuplicateTest.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/MultiplePoliciesOnRouteTest.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/RestEndpoint.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/RssDataFormat.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/SpringIdempotentConsumerTest.xml
rules-reviewed/camel3/camel2/tests/java-generic-information.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-468
https://issues.redhat.com/browse/WINDUPRULE-469
https://issues.redhat.com/browse/WINDUPRULE-465
To run tests run `mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=java-generic-information clean surefire-report:report`
Thanks !

Winduprule 465 468 469

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml
rules-reviewed/camel3/camel2/tests/data/java-generic-information/XsltAggregationStrategyTest.java
rules-reviewed/camel3/camel2/tests/java-generic-information.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-472
Run tests: `mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=java-generic-information clean surefire-report:report`
Thanks !

WINDUPRULE-472 Camel 3 XsltAggregationStrategy has been moved

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml
rules-reviewed/camel3/camel2/tests/data/java-generic-information/XsltAggregationStrategy-Blueprint.xml
rules-reviewed/camel3/camel2/tests/data/java-generic-information/XsltAggregationStrategy-Spring.xml
rules-reviewed/camel3/camel2/tests/java-generic-information.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-472
To run tests: `mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=java-generic-information clean surefire-report:report`
Thanks !

WINDUPRULE-472 Add Spring and Blueprint rules and tests

---

rules-reviewed/technology-usage/javaee-technology-tag.windup.groovy

https://issues.redhat.com/browse/WINDUPRULE-477 ([comment](https://issues.redhat.com/browse/WINDUPRULE-477?focusedCommentId=14004283&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14004283) in Jira adds description of the issue and about the fix)

WINDUPRULE-477 Changed 'javaee-technology-tag' phase

---

rules-reviewed/eap6/weblogic/weblogic.windup.xml
rules-reviewed/eap7/weblogic/weblogic.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-478
This can be tested locally running `mvn clean test -Dtest=WindupRulesLinksTest`

WINDUPRULE-478 Removed links to retired articles

---

rules-reviewed/eap7/eap72/maven-javax-to-jakarta.rhamt.xml

Issue: https://issues.redhat.com/browse/WINDUPRULE-479

[WINDUPRULE-479] maven-javax-to-jakarta links update

---

rules-reviewed/camel3/camel2/xml-generic-information.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-440

WINDUPRULE-440: fix typo

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-450

WINDUPRULE-450: fix typo

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-446

WINDUPRULE-446: fix typo

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-451

WINDUPRULE-451: fix typo

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-446

WINDUPRULE-446

---

rules-reviewed/camel3/camel2/tests/data/xml-generic-information/blueprint.xml
rules-reviewed/camel3/camel2/tests/data/xml-generic-information/context.xml
rules-reviewed/camel3/camel2/tests/xml-generic-information.windup.test.xml
rules-reviewed/camel3/camel2/xml-generic-information.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-511

WINDUPRULE-511: Add rules for Camel XML DSL changes

---

rules-reviewed/camel3/camel2/tests/data/xml-moved-components/application0/CoreMain.java
rules-reviewed/camel3/camel2/tests/xml-moved-components.windup.test.xml
rules-reviewed/camel3/camel2/xml-moved-components.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-480
To run tests: `mvn -DrunTestsMatching=xml-moved-components clean test`
Thanks !

 WINDUPRULE-480 org.apache.camel.main.Main has been moved

---

rules-reviewed/camel3/camel2/tests/data/xml-removed-components/pom.xml
rules-reviewed/camel3/camel2/tests/xml-removed-components.windup.test.xml
rules-reviewed/camel3/camel2/xml-removed-components.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-596
To run tests: `mvn -DrunTestsMatching=xml-removed-components clean test`
Thanks !

WINDUPRULE-596 camel-restlet has been removed

---

rules-reviewed/camel3/camel2/component-changes.windup.groovy
rules-reviewed/camel3/camel2/tests/component-changes.windup.test.xml
rules-reviewed/camel3/camel2/tests/data/component-changes/TelegramContext.java
rules-reviewed/camel3/camel2/tests/data/component-changes/telegram-context.xml
rules-reviewed/camel3/camel2/tests/data/java-generic-information/XsltAggregationStrategy-Spring.xml

https://issues.redhat.com/browse/WINDUPRULE-428

WINDUPRULE-428: camel-telegram auth token position changed. 

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml
rules-reviewed/camel3/camel2/tests/data/java-generic-information/ManagedCamelContext45Test.java
rules-reviewed/camel3/camel2/tests/java-generic-information.windup.test.xml
rules-reviewed/camel3/camel2/tests/xml-moved-components.windup.test.xml
rules-reviewed/camel3/camel2/xml-moved-components.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-494
To run tests: `mvn -DrunTestsMatching=xml-moved-components,java-generic-information clean test`
Thanks !

Winduprule 494

---

rules-reviewed/camel3/camel2/java-generic-information.windup.groovy
rules-reviewed/camel3/camel2/tests/data/java-generic-information/FileCopierWithCamel.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/MainExample.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/RouteBuilder.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/TestProcessor.java
rules-reviewed/camel3/camel2/tests/java-generic-information.windup.test.xml

Add new groovy rules into java-generic-information rule set:
https://issues.redhat.com/browse/WINDUPRULE-510
https://issues.redhat.com/browse/WINDUPRULE-504
https://issues.redhat.com/browse/WINDUPRULE-495
https://issues.redhat.com/browse/WINDUPRULE-491
https://issues.redhat.com/browse/WINDUPRULE-442
https://issues.redhat.com/browse/WINDUPRULE-490

Java-generic-infromation WINDUPRULE-490,442,491,495,504,510

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml
rules-reviewed/camel3/camel2/tests/data/java-generic-information/SimpleLanguageTest.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/SimpleLanguageTestBlueprint.xml
rules-reviewed/camel3/camel2/tests/data/java-generic-information/SimpleLanguageTestSpring.xml
rules-reviewed/camel3/camel2/tests/java-generic-information.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-503
To run tests: `mvn -DrunTestsMatching=java-generic-information clean test`
Thanks

WINDUPRULE-503 Simple Language

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml
rules-reviewed/camel3/camel2/tests/data/java-generic-information/PojoAnnotations47Test.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/PojoAnnotations48Test.java
rules-reviewed/camel3/camel2/tests/java-generic-information.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-496
To run tests `mvn -DrunTestsMatching=java-generic-information clean test`
Thanks !

WINDUPRULE-496: Pojo annotation rules

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml
rules-reviewed/camel3/camel2/tests/data/java-generic-information/CatalogCamelContext49Test.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/ExtendedCamelContext52Test.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/LoadRoute50Test.java
rules-reviewed/camel3/camel2/tests/data/java-generic-information/ModelInterface51Test.java
rules-reviewed/camel3/camel2/tests/java-generic-information.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-501
To run tests: `mvn -DrunTestsMatching=java-generic-information clean test -nsu`
Thanks !

Winduprule 501

---

rules-reviewed/camel3/camel2/tests/data/xml-removed-components/pom.xml
rules-reviewed/camel3/camel2/tests/xml-removed-components.windup.test.xml
rules-reviewed/camel3/camel2/xml-removed-components.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-512
to run tests: `mvn -DrunTestsMatching=xml-removed-components clean test -nsu`
Thanks !

WINDUPRULE-512 camel-maven-plugin has been split

---

rules-reviewed/camel3/camel2/tests/data/xml-moved-components/application0/MyRouteBuilder.java
rules-reviewed/camel3/camel2/tests/data/xml-moved-components/application0/blueprint.xml
rules-reviewed/camel3/camel2/tests/data/xml-moved-components/application0/context.xml
rules-reviewed/camel3/camel2/tests/xml-moved-components.windup.test.xml
rules-reviewed/camel3/camel2/xml-moved-components.windup.groovy

https://issues.redhat.com/browse/WINDUPRULE-613

WINDUPRULE-613: fix moved components rule

---

pom.xml

https://issues.redhat.com/browse/WINDUPRULE-612

WINDUPRULE-612 version upgrade

---

rules-reviewed/camel3/camel2/java-generic-information.windup.xml
rules-reviewed/camel3/camel2/tests/java-generic-information.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-636

WINDUPRULE-636: removing duplicate camel rule

---

rules-reviewed/quarkus/springboot/springboot-shell-to-quarkus.windup.xml
rules-reviewed/quarkus/springboot/tests/springboot-shell-to-quarkus.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-635

WINDUPRULE-635: spring shell to quarkus extension rule

---

rules-reviewed/quarkus/springboot/tests/springboot-cache-to-quarkus.windup.test.xml
rules-reviewed/quarkus/springboot/tests/springboot-di-to-quarkus.windup.test.xml
rules-reviewed/quarkus/springboot/tests/springboot-properties-to-quarkus.windup.test.xml

@jonathanvila As we've seen I've disabled this flag when not needed

refactor: disable sourceMode flag not needed

---

rules-reviewed/openshift/embedded-cache-libraries.windup.xml
rules-reviewed/openshift/java-rmi.windup.xml
rules-reviewed/openshift/java-rpc.windup.xml
rules-reviewed/openshift/jca.windup.xml
rules-reviewed/openshift/jni-native-code.windup.xml
rules-reviewed/openshift/local-storage.windup.xml
rules-reviewed/openshift/logging.windup.xml
rules-reviewed/openshift/mail.windup.xml
rules-reviewed/openshift/session.windup.xml
rules-reviewed/openshift/socket-communication.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-646
Ready for merge

Update openshift ruleset documentation

---

rules-reviewed/openshift/tests/java-rmi.windup.test.xml
rules-reviewed/openshift/tests/java-rpc.windup.test.xml
rules-reviewed/openshift/tests/jca.windup.test.xml
rules-reviewed/openshift/tests/jni-native-code.windup.test.xml
rules-reviewed/openshift/tests/local-storage.windup.test.xml
rules-reviewed/openshift/tests/logging.windup.test.xml
rules-reviewed/openshift/tests/mail.windup.test.xml
rules-reviewed/openshift/tests/session.windup.test.xml
rules-reviewed/openshift/tests/socket-communication.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-650

WINDUPRULE-650 fixed tests with new text

---

rules-reviewed/quarkus/springboot/springboot-mobile-to-quarkus.windup.xml
rules-reviewed/quarkus/springboot/tests/springboot-mobile-to-quarkus.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-629

WINDUPRULE-629: spring mobile to quarkus migration rule

---

rules-reviewed/quarkus/springboot/springboot-flo-to-quarkus.windup.xml
rules-reviewed/quarkus/springboot/tests/data/springboot-flo/springboot-flo-test.component.html
rules-reviewed/quarkus/springboot/tests/springboot-flo-to-quarkus.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-627

WINDUPRULE-627: spring flo to quarkus rule

---

rules-reviewed/quarkus/springboot/springboot-cloud-config-client-to-quarkus.windup.xml
rules-reviewed/quarkus/springboot/tests/data/springboot-cloud-config/pom.xml
rules-reviewed/quarkus/springboot/tests/springboot-cloud-config-client-to-quarkus.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-669

WINDUPRULE-669: spring cloud config client source analysis

---

rules-reviewed/quarkus/springboot/tests/springboot-mobile-to-quarkus.windup.test.xml

https://issues.redhat.com/browse/WINDUP-2771
Depends on https://github.com/windup/windup/pull/1398 to succeed in the builds

WINDUP-2771 Changed the test accordingly to reflect the expected behaviour

---

pom.xml

https://issues.redhat.com/browse/WINDUP-2789

WINDUP-2789: pom version change

---

rules-reviewed/quarkus/springboot/springboot-metrics-to-quarkus.windup.xml
rules-reviewed/quarkus/springboot/tests/data/springboot-metrics/pom.xml
rules-reviewed/quarkus/springboot/tests/springboot-metrics-to-quarkus.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-702

WINDUPRULE-702: prevent noisy rule triggering

---

rules-reviewed/quarkus1/quarkus1-10/quarkus1-11-mongodb-panache.windup.xml
rules-reviewed/quarkus1/quarkus1-10/tests/data/Person.java
rules-reviewed/quarkus1/quarkus1-10/tests/data/Rocker.java
rules-reviewed/quarkus1/quarkus1-10/tests/data/pom.xml
rules-reviewed/quarkus1/quarkus1-10/tests/quarkus1-11-mongodb-panache.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-711

WINDUPRULE-711 Quarkus Release 1.11 - MongoDB Panache

---

rules-reviewed/quarkus1/quarkus1-10/quarkus1-11-logging.windup.xml
rules-reviewed/quarkus1/quarkus1-10/tests/data/application.properties
rules-reviewed/quarkus1/quarkus1-10/tests/quarkus1-11-logging.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-707

WINDUPRULE-707 Quarkus Release 1.11 - Log min level

---

rules-reviewed/quarkus/springboot/springboot-properties-to-quarkus.windup.xml
rules-reviewed/quarkus/springboot/tests/data/springboot-properties/application-mysql.properties
rules-reviewed/quarkus/springboot/tests/data/springboot-properties/application.properties
rules-reviewed/quarkus/springboot/tests/springboot-properties-to-quarkus.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-695

WINDUPRULE-695: Spring properties to quarkus rules enhanced

---

rules-reviewed/quarkus1/quarkus1-11/quarkus1-12-distroless.windup.xml
rules-reviewed/quarkus1/quarkus1-11/tests/data/Dockerfile
rules-reviewed/quarkus1/quarkus1-11/tests/quarkus1-12-distroless.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-722

WINDUPRULE-722: quarkus1-12 distroless image rule

---

rules-reviewed/quarkus1/quarkus1-11/quarkus1-12-vertx.windup.xml
rules-reviewed/quarkus1/quarkus1-11/tests/data/vertx/VertxTestData.java
rules-reviewed/quarkus1/quarkus1-11/tests/quarkus1-12-vertx.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-718

WINDUPRULE-718 Quarkus 1.12 Vert.x

---

rules-reviewed/quarkus1/quarkus1-12/tests/quarkus1-13-native-image-goal.windup.test.xml

Changes to the path of the test file

Philipcattanach winduprule 733

---

rules-reviewed/eapxp/thorntail/replace_thorntail_boms.mta.xml
rules-reviewed/eapxp/thorntail/tests/data/data-replace_thorntail_boms/pom.xml
rules-reviewed/eapxp/thorntail/tests/replace_thorntail_boms.mta.test.xml

Issue: https://issues.redhat.com/browse/WINDUPRULE-738

[WINDUPRULE-738] (thorntail -> eap xp2+) replace thorntail boms

---

rules-reviewed/eapxp/thorntail/replace_thorntail_maven_plugin.mta.xml
rules-reviewed/eapxp/thorntail/tests/data/data-replace_thorntail_maven_plugin/pom.xml
rules-reviewed/eapxp/thorntail/tests/replace_thorntail_maven_plugin.mta.test.xml

Issue: https://issues.redhat.com/browse/WINDUPRULE-739

[WINDUPRULE-739] (thorntail -> eap xp2+) replace thorntail maven plugin

---

rules-reviewed/eap7/eap73/microprofile_removed_from_eap.mta.xml
rules-reviewed/eap7/eap73/tests/data/data-microprofile_removed_from_eap/pom.xml
rules-reviewed/eap7/eap73/tests/microprofile_removed_from_eap.mta.test.xml

Issue: https://issues.redhat.com/browse/WINDUPRULE-757

[WINDUPRULE-757] microprofile_removed_from_eap ruleset

---

rules-reviewed/technology-usage/non-xml-rules-technology-usage.rhamt.xml

Just found this typo while testing the API prototype.

Fix for a typo

---

rules-reviewed/eap8/eap7/javaee-to-jakarta-namespaces.windup.xml

https://issues.redhat.com/browse/WINDUP-3149
Enrich messages including the version to be updated.

[WINDUP-3149]: Java EE 8 to Jakarta EE9 - Rename deployment descriptor namespaces

---

rules-reviewed/eap8/eap7/javaee-to-jakarta-namespaces.windup.xml
rules-reviewed/eap8/eap7/tests/data/namespaces/permissions.xml
rules-reviewed/eap8/eap7/tests/javaee-to-jakarta-namespaces.windup.test.xml

https://issues.redhat.com/browse/WINDUP-3149

WINDUP-3149: rules for changing the 'versions' attribute for persistence and permission XML

---

rules-reviewed/openjdk11/openjdk8/removed-javaee-modules.windup.xml
rules-reviewed/openjdk11/openjdk8/tests/data/removed-javaee-modules/CompleteDukeApplication.java
rules-reviewed/openjdk11/openjdk8/tests/removed-javaee-modules.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-773

[WINDUPRULE-773] Add rule for corba removal

---

rules-reviewed/eap8/eap7/javaee-to-jakarta-namespaces.windup.xml
rules-reviewed/eap8/eap7/tests/data/namespaces/beans_jee7.xml
rules-reviewed/eap8/eap7/tests/data/namespaces/beans_jee8.xml
rules-reviewed/eap8/eap7/tests/data/namespaces/facelet-tag-lib_jee8.xml
rules-reviewed/eap8/eap7/tests/data/namespaces/faces-config_jee7.xml
rules-reviewed/eap8/eap7/tests/data/namespaces/faces-config_jee8.xml
rules-reviewed/eap8/eap7/tests/data/namespaces/permissions.xml
rules-reviewed/eap8/eap7/tests/data/namespaces/taglib.xml
rules-reviewed/eap8/eap7/tests/data/namespaces/web_jee7.xml
rules-reviewed/eap8/eap7/tests/data/namespaces/web_jee8.xml
rules-reviewed/eap8/eap7/tests/javaee-to-jakarta-namespaces.windup.test.xml

https://issues.redhat.com/browse/WINDUP-3149
This PR adds rules for changing the `version` of XML files. At the same time, it fixes some minor values within the `data` folder.

[WINDUP-3149]: Java EE 8 to Jakarta EE9 - Rename Versions

---

pom.xml
rules-reviewed/openrewrite/rewrite.yml

Needs to run with https://github.com/windup/windup-distribution/pull/74

WINDUP-3128: enable openrewrite run from cli

---

rules-reviewed/openjdk11/openjdk8/java-removals.windup.xml
rules-reviewed/openjdk11/openjdk8/removed-javaee-modules.windup.xml

See [jira ticket](https://issues.redhat.com/browse/WINDUPRULE-789).

[WINDUP-789] Fix source range of jdk11.jdk8 rules

---

rules-reviewed/camel3/camel2/tests/data/java-generic-information/pom.xml
rules-reviewed/camel3/camel2/tests/data/xml-renamed-components/pom.xml

Fixing [WINDUP-3233](https://issues.redhat.com/browse/WINDUP-3233) in the windup project has exposed some failing tests that this PR fixes.
Merge this first:
- https://github.com/windup/windup/pull/1442

[WINDUP-3233] Fix tests

---

.github/workflows/pr_build_jdk11.yml

See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3215)

[WINDUP-3215] Fix build

---

rules-reviewed/technology-usage/integration-technology-usage.windup.xml
rules-reviewed/technology-usage/integration.windup.xml
rules-reviewed/technology-usage/tests/data/integration/JavaDSLFileCopyConfig.java
rules-reviewed/technology-usage/tests/data/integration/http-inbound-config.xml
rules-reviewed/technology-usage/tests/integration.windup.test.xml

Another tech tags change. This one is no reliant on any of the new tiers.

WINDUPRULE-807 - Tech Tags - Spring Integration

---

rules-reviewed/technology-usage/embedded-framework.windup.xml
rules-reviewed/technology-usage/markup-technology-usage.windup.xml
rules-reviewed/technology-usage/tests/data/embedded-framework/springboot-flo/editor.component.foo
rules-reviewed/technology-usage/tests/data/embedded-framework/springboot-flo/editor.component.ts
rules-reviewed/technology-usage/tests/data/embedded-framework/springboot-flo/springboot-flo-test.component.html
rules-reviewed/technology-usage/tests/embedded-framework.windup.test.xml
rules-reviewed/technology-usage/tests/markup-technology-usage.windup.test.xml

A new technology tag that is allocated to an existing (rather than new) category.

WINDUPRULE-806 - Tech Tags - Spring Boot Flo

---

rules-reviewed/quarkus/springboot/springboot-plugins-to-quarkus.windup.xml
rules-reviewed/quarkus/springboot/tests/data/springboot-plugins/pom.xml
rules-reviewed/quarkus/springboot/tests/springboot-plugins-to-quarkus.windup.test.xml

See [WINDUPRULE-782](https://issues.redhat.com/browse/WINDUPRULE-782).

[WINDUPRULE-782] Create new rule to check for spring-boot-maven-plugin dependency

---

rules-reviewed/technology-usage/embedded-framework-technology-usage.windup.xml
rules-reviewed/technology-usage/embedded-framework.windup.xml
rules-reviewed/technology-usage/tests/data/embedded-framework/ScheduledAnnotationExample.java
rules-reviewed/technology-usage/tests/embedded-framework-technology-usage.windup.test.xml
rules-reviewed/technology-usage/tests/embedded-framework.windup.test.xml

Hi @m-brophy this is the last of the PR's for new technology tags for the Spring Technologies that are referenced in the SB2Quarkus rules.
Thanks for all of the reviews you have been doing on these rulesets.
Cheers,
Phil

Winduprule 810

---

rules-reviewed/quarkus/springboot/springboot-plugins-to-quarkus.windup.xml

See [WINDUPRULE-782](https://issues.redhat.com/browse/WINDUPRULE-782).

[WINDUP-782] Reword rule message

---

README.md

Information on rules-reviewed and rules-generated

Adding some information about some subdirectories

---

rules-reviewed/quarkus/springboot/springboot-metrics-to-quarkus.windup.xml
rules-reviewed/quarkus/springboot/springboot-properties-to-quarkus.windup.xml
rules-reviewed/quarkus/springboot/tests/data/springboot-metrics/application.properties
rules-reviewed/quarkus/springboot/tests/springboot-metrics-to-quarkus.windup.test.xml

One of several configuration properties mapping rules for SB2Quarkus data mapping

WINDUPRULE-828 Map Prometheus Metrics endpoint

---

rules-reviewed/eap6/glassfish/java-glassfish.windup.groovy

https://issues.redhat.com/browse/WINDUP-3307

WINDUP-3307 Fixed issue when 'default' variable is not available

---

rules-reviewed/openjdk11/openjdk8/java-removals.windup.xml
rules-reviewed/openjdk11/openjdk8/tests/data/java-removals/Base64Removals.java
rules-reviewed/openjdk11/openjdk8/tests/java-removals.windup.test.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-791).

[WINDUPRULE-791] Add rule for detecting usage of sun.misc base64 encoders

---

rules-reviewed/openjdk11/openjdk8/java-removals.windup.xml

See comments in [https://github.com/windup/windup-rulesets/pull/637](https://github.com/windup/windup-rulesets/pull/637) and [https://issues.redhat.com/browse/WINDUPRULE-785](https://issues.redhat.com/browse/WINDUPRULE-785).

[WINDUPRULE-785] Change hint suggestion according to current JDK 11 API

---

rules-reviewed/openrewrite/jakarta/javax/xml/rewrite.yml

javax-jakarta openrewrite yaml recipe to migrate persistence.xml using new ChangeTagAttribute java recipe

WINDUP-3293: persistence.xml recipe

---

rules-reviewed/rhr/springboot/springboot.rhamt.xml
rules-reviewed/rhr/springboot/tests/springboot.rhamt.test.xml

See [https://issues.redhat.com/browse/WINDUPRULE-837](https://issues.redhat.com/browse/WINDUPRULE-837).

[WINDUPRULE-837] Update target rhr ruleset to reflect the springboot version range supported

---

rules-reviewed/filemappings/default-package-to-organization-names.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-841

WINDUPRULE-841 'org.primefaces' package mapping

---

rules-reviewed/technology-usage/embedded-framework-technology-usage.windup.xml
rules-reviewed/technology-usage/tests/embedded-framework-technology-usage.windup.test.xml

Hi Juanma, 
This is the changes to add the Spring Cloud Function to the Tech Reports.
Thanks,
Phil

WINDUPRULE-839 Spring Cloud Function added to Technology Reports

---

rules-reviewed/filemappings/default-package-to-organization-names.windup.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3310).

[WINDUP-3310] Add dozer to list of package mappings

---

rules-reviewed/eap6/weblogic/weblogic-xml-descriptors.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-846

WINDUPRULE-846 rule 'weblogic-xml-descriptor-12000': fixed broken link

---

rules-reviewed/openrewrite/jakarta/javax/bootstrapping/rewrite.yml
rules-reviewed/openrewrite/jakarta/javax/xml/rewrite.yml

https://issues.redhat.com/browse/WINDUP-3362

WINDUP-3362: rename spi bootstrapping file

---

.github/workflows/pr_build_jdk11.yml

https://issues.redhat.com/browse/WINDUPRULE-887

WINDUPRULE-887: upgrade ubuntu version

---

rules/rules-reviewed/openshift/java-rmi.windup.xml

https://issues.redhat.com/browse/WINDUP-3490

WINDUP-3490: replace cloud tag with cloud-readiness

---

rules/rules-reviewed/rhr/springboot/springboot.rhamt.xml

Mark - I have resubmitted this PR because the structure of the project had moved on

WINDUPRULE-890 minor update to rhr rules for versions of SB supported

---

rules/rules-reviewed/eap8/eap7/empty-beans-xml.windup.xml
rules/rules-reviewed/eap8/eap7/tests/data/empty-beans-xml/beans.xml
rules/rules-reviewed/eap8/eap7/tests/empty-beans-xml.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-892
with thanks to @bstansberry, based on his rule at https://github.com/bstansberry/windup-rulesets/commit/769eb0f1a3d8ab2674cfb998945e42202e220a2a

WINDUPRULE-892: new jakarta rule for empty beans.xml file

---

rules/pom.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-zipkin.windup.xml

See [https://issues.redhat.com/browse/WINDUPRULE-889](https://issues.redhat.com/browse/WINDUPRULE-889).

[WINDUPRULE-889] Fix azure rules

---

rules/src/test/java/org/jboss/windup/rules/tests/WindupRulesLinksTest.java

See [JIRA ticket](https://issues.redhat.com/browse/WINDUPRULE-913).

[WINDUPRULE-913] Temporary fix for PKIX cert issue

---

rules/rules-reviewed/azure/azure-file-system.windup.xml
rules/rules-reviewed/azure/azure-password.windup.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-cache.windup.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-database.windup.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-eureka.windup.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-feign.windup.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-identity-provider.windup.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-jms-broker.windup.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-schedule-job.windup.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-static-content.windup.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-zipkin.windup.xml

All the Azure rules for Spring are now also available for Azure Container Apps

Make Azure rules for Spring available for Azure Containers Apps

---

rules/rules-reviewed/quarkus/springboot/springboot-di-to-quarkus.windup.xml
rules/rules-reviewed/quarkus/springboot/tests/data/springboot-di/beans.xml
rules/rules-reviewed/quarkus/springboot/tests/springboot-di-to-quarkus.windup.test.xml

Hi Mark,
Just updating the SB2Quarkus PRs that were on hold, and need to reflect the new structure of the project

WINDUPRULE-885 Spring Boot DI PR updated to reflect new repo structure

---

rules/rules-reviewed/technology-usage/discovery-target.windup.xml

https://issues.redhat.com/browse/WINDUP-3558

Added 'discovery' target in an empty ruleset

---

.github/workflows/pr_build_jdk11.yml

Now in ~25 minutes we have all the tests done (if I'm not wrong/missing anything in the tests' patterns :sweat_smile: )

GitHub jobs enhancements

---

rules/rules-reviewed/azure/springboot/spring-boot-to-azure-zipkin.windup.xml
rules/rules-reviewed/eap8/eap7/login-modules.windup.xml
rules/rules-reviewed/eap8/eap7/tests/data/login-modules/LoginModules.java
rules/rules-reviewed/eap8/eap7/tests/login-modules.windup.test.xml

See [https://issues.redhat.com/browse/WINDUPRULE-904](https://issues.redhat.com/browse/WINDUPRULE-904).

[WINDUPRULE-904] LoginModules

---

rules/rules-reviewed/technology-usage/ejb-technology-usage.windup.xml
rules/rules-reviewed/technology-usage/ejb.windup.xml
rules/rules-reviewed/technology-usage/tests/data/ejb/EJBTimerSchedule.java
rules/rules-reviewed/technology-usage/tests/data/ejb/EJBTimerTimeout.java
rules/rules-reviewed/technology-usage/tests/ejb-technology-usage.windup.test.xml

See https://issues.redhat.com/browse/WINDUPRULE-924

Detect EJB Timer usage

---

rules/rules-reviewed/azure/springboot/spring-boot-to-azure-zipkin.windup.xml

Hi Mark, 
A very simple PR.
Could you give it a quick review and if you are happy with it then merge it and update the status of the Jira

WINDUPRULE-931 - badly titled link

---

rules/rules-reviewed/eap8/eap7/jakarta-cdi.windup.xml
rules/rules-reviewed/eap8/eap7/tests/data/jakarta-cdi/JakartaCDI.java
rules/rules-reviewed/eap8/eap7/tests/jakarta-cdi.windup.test.xml

See [https://issues.redhat.com/browse/WINDUPRULE-905](https://issues.redhat.com/browse/WINDUPRULE-905).

[WINDUPRULE-905] Create Jakarta CDI rules

---

rules/rules-reviewed/eap8/eap6/eap8-faces.windup.xml

Added some links from the eap-faces rulesets to the relevant sections of Customer Portal Migration Article https://access.redhat.com/articles/6980265#faces

WINDUPRULE-938 add link to migration article from eap-faces rules

---

rules/rules-reviewed/eap8/eap7/javax-to-jakarta-servlet.windup.xml
rules/rules-reviewed/eap8/eap7/tests/data/servlet/SingleThreadModelImpl.java
rules/rules-reviewed/eap8/eap7/tests/javax-to-jakarta-package.windup.test.xml
rules/rules-reviewed/eap8/eap7/tests/javax-to-jakarta-servlet.windup.test.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-896).

[WINDUPRULE-896] Jakarta servlet related rules

---

rules/rules-reviewed/azure/springboot/spring-boot-to-azure-cache.windup.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-feign.windup.xml
rules/rules-reviewed/quarkus/springboot/springboot-shell-to-quarkus.windup.xml

These 3 URLs return a 308 because they do not have a `/` at the end. I'm adding the missing `/` so it returns a 200 instead

Fixing URLs

---

rules/rules-reviewed/azure/springboot/spring-boot-to-azure-cache.windup.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-feign.windup.xml
rules/rules-reviewed/openjdk17/openjdk11/lombok.windup.xml
rules/rules-reviewed/openjdk17/openjdk11/tests/data/lombok/pom.xml
rules/rules-reviewed/openjdk17/openjdk11/tests/lombok.windup.test.xml
rules/rules-reviewed/quarkus/springboot/springboot-shell-to-quarkus.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-946

Lombok <1.18.22 is not compatible with JDK 17

---

rules/rules-reviewed/eap8/eap7/jakarta-ws-rs.windup.xml
rules/rules-reviewed/eap8/eap7/tests/data/ws-rs/WsRs.java
rules/rules-reviewed/eap8/eap7/tests/jakarta-ws-rs.windup.test.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-895).

[WINDUPRULE-895] Jakarta restful webservices

---

rules/rules-reviewed/eap8/eap7/jakarta-el.windup.xml
rules/rules-reviewed/eap8/eap7/tests/data/jakarta-el/JakartaEL.java
rules/rules-reviewed/eap8/eap7/tests/jakarta-el.windup.test.xml
rules/rules-reviewed/eap8/eap7/tests/javax-to-jakarta-package.windup.test.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-906)

[WINDUPRULE-906] Rules for javax/jakarta EL

---

rules/rules-reviewed/eap8/eap7/jakarta-el.windup.xml
rules/rules-reviewed/eap8/eap7/tests/data/jakarta-el/JakartaEL.java
rules/rules-reviewed/eap8/eap7/tests/jakarta-el.windup.test.xml
rules/rules-reviewed/eap8/eap7/tests/javax-to-jakarta-package.windup.test.xml

Base PR https://github.com/windup/windup-rulesets/pull/860
See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-906)

[releases/6.1.z][WINDUPRULE-906] Rules for javax/jakarta EL

---

rules/rules-reviewed/eap8/eap7/jakarta-soap.windup.xml
rules/rules-reviewed/eap8/eap7/tests/data/jakarta-soap/JakartaSOAP.java
rules/rules-reviewed/eap8/eap7/tests/jakarta-soap.windup.test.xml
rules/rules-reviewed/eap8/eap7/tests/javax-to-jakarta-package.windup.test.xml

Base PR https://github.com/windup/windup-rulesets/pull/863
See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-911).

[releases/6.1.z] [WINDUPRULE-911] Rules for Jakarta SOAP 3.0

---

rules/rules-reviewed/eap8/eap6/eap8-xml-binding.windup.xml
rules/rules-reviewed/eap8/eap6/tests/data/xml-binding/META-INF/services/javax.xml.bind.JAXBContext
rules/rules-reviewed/eap8/eap6/tests/data/xml-binding/SunApiPackageTest.java
rules/rules-reviewed/eap8/eap6/tests/data/xml-binding/SunV2PackageTest.java
rules/rules-reviewed/eap8/eap6/tests/data/xml-binding/jaxb.properties
rules/rules-reviewed/eap8/eap6/tests/data/xml-binding/pom.xml
rules/rules-reviewed/eap8/eap6/tests/data/xml-binding/test.xjb
rules/rules-reviewed/eap8/eap6/tests/eap8-xml-binding.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-897

WINDUPRULE-897: Rules to move to Jakarta XML Binding 4.0

---

pom.xml
rules-themed/pom.xml
rules-themed/rules-mta/pom.xml
rules-themed/rules-mtr/pom.xml
rules-themed/rules-tackle/pom.xml
rules-themed/rules-windup/pom.xml
rules/pom.xml

Reverts https://github.com/windup/windup-rulesets/commit/25a486fc1f884f777f06a408dd9a493262532ee3 changing 7 files with 8 additions and 8 deletions like in the reverted commit.

Restored version 6.1.3-SNAPSHOT

---

rules/rules-reviewed/eap8/eap7/javax-to-jakarta-servlet.windup.xml
rules/rules-reviewed/eap8/eap7/tests/data/servlet/SingleThreadModelImpl.java
rules/rules-reviewed/eap8/eap7/tests/javax-to-jakarta-package.windup.test.xml
rules/rules-reviewed/eap8/eap7/tests/javax-to-jakarta-servlet.windup.test.xml

backport https://github.com/windup/windup-rulesets/pull/785

[releases/6.1.z] [WINDUPRULE-896] Jakarta servlet related rules (#785)

---

rules/rules-reviewed/eap8/eap7/keycloak-openid.windup.xml
rules/rules-reviewed/eap8/eap7/tests/data/keycloak-openid/keycloak.json
rules/rules-reviewed/eap8/eap7/tests/data/keycloak-openid/web.xml
rules/rules-reviewed/eap8/eap7/tests/keycloak-openid.windup.test.xml

backport https://github.com/windup/windup-rulesets/pull/824

[releases/6.1.z] [WINDUPRULE-903] Keycloak/OpenID rules (#824)

---

rules/rules-reviewed/technology-usage/configuration-management-technology-usage.windup.xml
rules/rules-reviewed/technology-usage/configuration-management.windup.xml
rules/rules-reviewed/technology-usage/tests/configuration-management-technology-usage.windup.test.xml
rules/rules-reviewed/technology-usage/tests/configuration-management.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-964

WINDUPRULE-964 Fixed application properties file technology rule

---

rules/rules-reviewed/eap8/eap7/hibernate-search-6.1.windup.xml
rules/rules-reviewed/eap8/eap7/tests/data/hibernate-search-61/pom.xml
rules/rules-reviewed/eap8/eap7/tests/hibernate-search-6.1.windup.test.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-963).

[WINDUPRULE-963] Improve hibernate-search-6.1-00010

---

.github/workflows/pr_build_jdk11.yml
rules/pom.xml
rules/rules-reviewed/openjdk17/openjdk11/tests/removed-classes.windup.test.xml
rules/rules-reviewed/openjdk17/openjdk11/tests/removed-packages.windup.test.xml

https://issues.redhat.com/browse/WINDUP-3602
[Relaxed OpenJDK17 rules' tests](https://github.com/windup/windup-rulesets/pull/893/commits/3fb9c842d4316658f58261639cc378d03dd4d618) needs a dedicated PR for fixing the issues properly

WINDUP-3602 Run project's tests on JDK 11 and 17

---

rules/rules-reviewed/eap8/hibernate6.windup.technologytransformer.xml

https://issues.redhat.com/browse/WINDUPRULE-969

WINDUPRULE-969 'hibernate6' migration target alias

---

rules/rules-reviewed/eap8/eap7/jakarta-faces.windup.xml
rules/rules-reviewed/eap8/eap7/tests/data/jakarta-faces/JSFBean.java
rules/rules-reviewed/eap8/eap7/tests/data/jakarta-faces/Producer.java
rules/rules-reviewed/eap8/eap7/tests/jakarta-faces.windup.test.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-920).
:warning: Merge [this PR](https://github.com/windup/windup/pull/1612) first.

[WINDUPRULE-920] Jakarta Faces rule

---

rules/rules-reviewed/eap8/eap7/javax-to-jakarta-servlet.windup.xml
rules/rules-reviewed/eap8/eap7/legacy-vault.windup.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-959).

[WINDUPRULE-959] Add missing links

---

rules/rules-reviewed/eap8/eap7/jakarta-faces.windup.xml
rules/rules-reviewed/eap8/eap7/tests/jakarta-faces.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-920

[WINDUPRULE-920] Fix typo

---

rules/rules-reviewed/technology-usage/security-technology-usage.windup.xml

https://issues.redhat.com/browse/WINDUPRULE-972

WINDUPRULE-972 technology-usage-security-01000: added 'iteration'

---

rules/rules-reviewed/eap8/eap7/hibernate6.windup.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-956).
Trade-off to improve performance. `filecontent` conditions that look in every file are very slow. Even though these properties can appear in different places, they are usually defined in the particular files mentioned in the rule.
New timings:
```
2023-03-28 12:33 [387/1323] MigrationRulesPhase - hibernate6 - hibernate-00005
2023-03-28 12:33 [388/1323] MigrationRulesPhase - hibernate6 - hibernate-00010
2023-03-28 12:33 [389/1323] MigrationRulesPhase - hibernate6 - hibernate6-00020
2023-03-28 12:33 [390/1323] MigrationRulesPhase - hibernate6 - hibernate6-00030
2023-03-28 12:33 [391/1323] MigrationRulesPhase - hibernate6 - hibernate6-00040
2023-03-28 12:33 [392/1323] MigrationRulesPhase - hibernate6 - hibernate6-00050 …
```

[WINDUPRULE-956] Narrow down properties rules to look only in some files

---

rules/rules-reviewed/azure/springboot/spring-boot-to-azure-eureka.windup.xml
rules/rules-reviewed/azure/springboot/spring-boot-to-azure-zipkin.windup.xml

backport
- https://github.com/windup/windup-rulesets/pull/801
- https://github.com/windup/windup-rulesets/pull/913

[releases/6.1.z] Fixed 'spring-boot-to-azure-eureka-01000' rule's link

---

rules/rules-reviewed/technology-usage/tests/configuration-management-technology-usage.windup.test.xml
rules/rules-reviewed/technology-usage/tests/database-technology-usage.windup.test.xml
rules/rules-reviewed/technology-usage/tests/embedded-framework-technology-usage.windup.test.xml
rules/rules-reviewed/technology-usage/tests/integration-technology-usage.windup.test.xml
rules/rules-reviewed/technology-usage/tests/jta-technology-usage.windup.test.xml
rules/rules-reviewed/technology-usage/tests/logging-technology-usage.windup.test.xml
rules/rules-reviewed/technology-usage/tests/markup-technology-usage.windup.test.xml
rules/rules-reviewed/technology-usage/tests/mvc-technology-usage.windup.test.xml
rules/rules-reviewed/technology-usage/tests/non-xml-rules-technology-usage.rhamt.test.xml
rules/rules-reviewed/technology-usage/tests/security-technology-usage.windup.test.xml
rules/rules-reviewed/technology-usage/tests/web-technology-usage.windup.test.xml

https://issues.redhat.com/browse/WINDUPRULE-985
Depends on:
- https://github.com/windup/windup/pull/1663
Basically this PR properly set the values for the `number-found` attributes to reflect the values a user can see for the same technology in the reports.
This build https://github.com/windup/windup/actions/runs/4936347232/jobs/8823923302?pr=1663 contains the full list of 32 failed tests in this project with the fix in place:
```
2023-05-10T11:58:06.2144303Z Failed tests: 
2023-05-10T11:58:06.2166782Z   WindupRulesTest.testWindupRules:151 
2023-05-10T11:58:06.2167577Z 	Error with test: technology-usage-logging-00010-test
2023-05-10T11:58:06.2168204Z 	Cause: (Rule: technology-usage-logging-00010-test) Assertion failed: Expected data not found for rule technology-usage-logging-00010 …
```

WINDUPRULE-985 Fixed 'number-found' consistently with actual values in the reports

---

rules/pom.xml
rules/src/test/java/org/jboss/windup/rules/tests/WindupRulesMultipleTests.java
rules/src/test/java/org/jboss/windup/rules/tests/WindupRulesTest.java

https://issues.redhat.com/browse/WINDUP-3879
- Requires https://github.com/windup/windup/pull/1668

[WINDUP-3879] - New PF4 Reports - Source Code Report not active with yaml files

---

rules/pom.xml

https://issues.redhat.com/browse/WINDUPRULE-1009

WINDUPRULE-1009 More memory for tests with JDK 9+

---

rules/rules-reviewed/technology-usage/database-technology-usage.windup.xml
rules/rules-reviewed/technology-usage/tests/database-technology-usage.windup.test.xml
rules/rules-reviewed/technology-usage/tests/database.windup.test.xml

Database rules are mixed up. Cassandra rule test is duplicate

Fix the database rules and tests numbers

---

rules/rules-reviewed/openjdk21/openjdk17/dynamic-agents.windup.xml
rules/rules-reviewed/openjdk21/openjdk17/tests/data/dynamic-agents/DynamicAgents.java
rules/rules-reviewed/openjdk21/openjdk17/tests/dynamic-agents.windup.test.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUPRULE-1016).

[WINDUPRULE-1016] Rule for dynamic loading of agents

---

rules/rules-reviewed/openjdk21/openjdk17/tests/data/utf-8-by-default/FileReaderExample.java
rules/rules-reviewed/openjdk21/openjdk17/tests/data/utf-8-by-default/FileWriterExample.java
rules/rules-reviewed/openjdk21/openjdk17/tests/data/utf-8-by-default/FormatterExample.java
rules/rules-reviewed/openjdk21/openjdk17/tests/data/utf-8-by-default/InputStreamReaderExample.java
rules/rules-reviewed/openjdk21/openjdk17/tests/data/utf-8-by-default/OutputStreamWriterExample.java
rules/rules-reviewed/openjdk21/openjdk17/tests/data/utf-8-by-default/PrintStreamExample.java
rules/rules-reviewed/openjdk21/openjdk17/tests/data/utf-8-by-default/ScannerExample.java
rules/rules-reviewed/openjdk21/openjdk17/tests/data/utf-8-by-default/URLDecoderExample.java
rules/rules-reviewed/openjdk21/openjdk17/tests/data/utf-8-by-default/URLEncoderExample.java
rules/rules-reviewed/openjdk21/openjdk17/tests/utf-8-by-default.windup.test.xml
rules/rules-reviewed/openjdk21/openjdk17/utf-8-by-default.windup.xml

Hi @jmle Can you review this OpenJDK 21 PR please.

WINDUPRULE-1013 OpenJDK21 UTF-8 character set used by default

---

rules/rules-reviewed/eap7/weblogic/weblogic-catchall.windup.xml
rules/rules-reviewed/eap7/weblogic/weblogic-ejb.windup.xml
rules/rules-reviewed/eap7/weblogic/weblogic-ignore-references.windup.xml
rules/rules-reviewed/eap7/weblogic/weblogic-jms.windup.xml
rules/rules-reviewed/eap7/weblogic/weblogic-services.windup.xml
rules/rules-reviewed/eap7/weblogic/weblogic-webapp.windup.xml
rules/rules-reviewed/eap7/weblogic/weblogic-webservices.windup.xml
rules/rules-reviewed/eap7/weblogic/weblogic-xml-descriptors.windup.xml
rules/rules-reviewed/eap7/weblogic/weblogic.windup.xml
rules/rules-reviewed/eap7/websphere/websphere-catchall.windup.xml
rules/rules-reviewed/eap7/websphere/websphere-ignore-references.windup.xml
rules/rules-reviewed/eap7/websphere/websphere-mqe.windup.xml
rules/rules-reviewed/eap7/websphere/websphere-xml.windup.xml

[WINDUPRULE-1036](https://issues.redhat.com/browse/WINDUPRULE-1036)

update supported eap target version

---

rules/rules-reviewed/eap7/eap72/deprecated-singletonpolicy.rhamt.xml
rules/rules-reviewed/eap7/eap72/maven-artemis-jms-client.rhamt.xml
rules/rules-reviewed/eap7/eap72/maven-javax-to-jakarta.rhamt.xml
rules/rules-reviewed/eap7/eap72/maven-jboss-rmi-api_1.0_spec.rhamt.xml
rules/rules-reviewed/eap7/eap72/move-to-microprofile-rest-client-1.3.rhamt.xml
rules/rules-reviewed/eap7/eap72/singleton-sessionbean.rhamt.groovy
rules/rules-reviewed/eap7/eap72/singleton-sessionbean.rhamt.xml
rules/rules-reviewed/eap7/eap73/microprofile_removed_from_eap.mta.xml

Basic change to make these rulesets more accurately targeted

WINDUPRULE-1038 EAP 7.3 and 7.4 Target correction

---

rules/rules-reviewed/eap6/java-ee/seam/seam-java.windup.xml

https://issues.redhat.com/browse/WINDUP-4152

replace failing link
